### ISSUE TITLE
wifiphiser not closing properly

### ISSUE THREAD

**Issue by Tsirantonakis** [wifiphisher/wifiphisher#1002]
i am running the latest version on kali
after the victim connects to the AP if esape key is pressed to exit it prints this:
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

but it stays on closing with the terminal running and never actually closes, meaning that if i kill it and
rerun wifiphiser i will get a address already in use for the http server

**Comment by rickjr** [comment]
I have the same problem, try:
`service` network-manager restart
Or disconnect the cable from the wi-fi adapter

**Comment by sophron** [comment]
I think @hpanago mentioned something similar. I'll have a look.

**Comment by stopdick** [comment]
Yeap, same thing happening to me

**Comment by sophron** [comment]
CC: @blackHatMonkey 

This bug was introduced because of the refactoring in #976. Two loops and one `break` statement did not allow the thread to exit properly. Fix is: 9e64ab365411061de78075935666f73159ca7c58

Let's this be a lesson for any future refactoring. There is this proverb <a href="https://en.wiktionary.org/wiki/if_it_ain%27t_broke,_don%27t_fix_it">"If it ain't broke, don't fix it"</a>. While I don't exactly advocate that, from now on I'll be very hesitant with Pull Requests that refactor existing code that has been tested and appears to be working properly.

It's not a deal if we can initialize one less variable somewhere in the code. The current code has one important property: It has been tested by hundreds of users. When we are refactoring, we are essentially giving that property away.

Someone may argue that the problem is code reviews and that we should be more careful before merging Pull Requests. The thing is that we are open source developers, we are doing what we do in our free time and usually there is no free time available. We don't have the energy nor the time to support extensive code reviews on newly refactored code.

Of'course Pull Requests that significantly increase the software's performance or extensibility are always welcome.

**Comment by Loxxx666** [comment]
I got Ubuntu 22 and i fixed it with this command: sudo apt install net-tools
