### ISSUE TITLE
How to Disable KARMA

### ISSUE THREAD

**Issue by koloss6** [wifiphisher/wifiphisher#1006]
In a situation where a changing essid would make the victim suspicious or automatic connection to known networks is not preferred, is there a way to disable KARMA and keep a static name for the Evil twin

**Comment by sophron** [comment]
Thanks for proposing this. We will add a switch soon.

**Comment by koloss6** [comment]
Thank you

P.S: can you please tell me which version you added the KARMA feature? 1.3?

**Comment by anakin1028** [comment]
Also you can use `-fH` to use the system hostapd, then there will be no KARMA  attack

**Comment by sophron** [comment]
I added argument `-dK` or `--disable-karma` that disables KARMA attack.

**Comment by Delfino520** [comment]
> I added argument `-dK` or `--disable-karma` that disables KARMA attack.

@sophron Hi, bro I want to introduce a interesting project to you. I just get the code online in China, it is a firmware working on ESP8226, the work principle is similar with linset, wifiphisher or fusion, the different is it works on ESP8226, i call it WIFI BAIT. I am not developer and i do not know anything about programming. There are no similar projects on Github. I think it is a interest project with unknown author, but i confirm that the author is a Chinese people, i have translated Chinese construction into English, if you are interested in it, please contract me. I hope you can put it on Github and try to improve it with developer from all over the world. If you decide to improve this project, i strongly recommend you to combine the webpages function with this project, because in this project you cannot choose webpage you like, such as Browser Connection Reset, Firmware Upgrade page, Browser plugin update and so on. By the way the webpage in this project is too ugly.I have attach all the document & software needed in the email, hope can hear you soon.  I email you today but my email get rejected,  My email address : s386106832@gmail.com

**Comment by sophron** [comment]
@Delfino520 What you are proposing is completely irrelevant with this thread. I have no free time available to support another project but you can contact me via email if you need anything.

I'm closing this issue since it is now resolved.
