### ISSUE TITLE
Evil twin plus wifi_connect

### ISSUE THREAD

**Issue by whitehat2810** [wifiphisher/wifiphisher#1019]
Don't know if this is a issue or more a feature request. Currently the AP selection phase is skipped when the "-e / -pK" Option is given for creating an evil twin. This has two downsides: the wifi_connect pishing scenario asks the victim for the password of the SSID which already is known to the attacker and no Deauth is done.

I have the following Scenario in Mind:
* The target device is regularly connected to a public encrypted wifi in a cafe
* Now the attacker knows the credentials of that "cafe Wifi" (because they are printed out in that cafe)
* The target device now is connected to a private network
* the attacker creates a Evil twin of the "cafe Wifi"
* then the attacker constantly sends deauth frames towards the victim
* the victim disconnects from the private network and connects to the evil twin of the encrypted cafe wifi
* now the phishing scenario "wifi_connect" asks for the password of the private network (instead of the already known "cafe network" credentials

In order to archive this, the AP selection phase should ask for a target network (the private network in that case), then deauth extension should be launched in order to shut down the private network connections and the phishing scenario needs to ask for the target AP credentials.

**Comment by sophron** [comment]
Thanks for proposing this.

I'll implement it soon.

**Comment by sophron** [comment]
I added a new argument `--phishing-essid` or `-pE`. This will set the ESSID that you provide in your phishing page.

I also adjusted `--deauth-essid` or `-dE`. You can now set an ESSID and Wifiphisher will deauth all APs in the corresponding WLAN.

You can mount your attack the following way:

`wifiphisher --essid "cafe Wifi" --preshared-key 12345678 --phishing-essid "cafe network" --deauth-essid "cafe network"`

Let me know if it works.

**Comment by sophron** [comment]
Hmmm, I may know what the issue is. When we specify `--deauth-essid`, the card in monitor mode will hop every available channel to look for APs broadcasting the specified ESSID. This will be slow in cases that there is only one AP that we want to deauth. 

I think we should introduce one more option `--deauth-channel`. I'll do it soon.

**Comment by sophron** [comment]
I had another look. It seems to work fine to me as it is.

Here's the catch: If you are using only one card and you spawn your rogue Access Point "cafe Wifi" on channel 6 (which is the default channel), you won't be able to deauth "cafe network" if it's on a different channel.

If that's the case you have two options:

1. Spawn your rogue AP on the same channel as "cafe network". For now, you can edit `constants.py` and change the value "CHANNEL" manually.

2. Use a second Wi-Fi card. This will allow Wifiphisher to perform channel hopping. Even if the rogue AP remains on channel 6, the second card will hop through all available channels and disconnect any victims belong to "cafe Wifi", even they are on a different channel.

Let me know how it goes.

**Comment by whitehat2810** [comment]
@sophron Thanks for the analysis. I'm using two wifi adapters for my tests.

I did a bit more of tracing (BTW: ```wlan.fc == 0xc008 || wlan.fc == 0xa008``` was the wireshark display filter I was looking for).

You are right, the deauthentication is done by wifiphisher as expected. I can see bursts of 10s deauthentication frames every 30s on the channel, which is used by the target AP and my test Laptop. Still the bursts seems to not always cause a disconnect. **But if I wait a bit longer, then the burst actually cause a disconnect**. But afterwards the test PC is reconnecting to the original Wifi immediately instead of connecting to my rogue AP. This may be due to the fact that everything is lined up on a lab desk and the rogue AP has the same signal strength as the target AP. I will lower the tx power of the test AP and check if that helps.

Still, when launching mdk3 in parallel to wifiphisher, the Test laptop disconnects from the target AP much quicker and afterwards connects to the rogue AP, even if the rogue AP has same signal level as the target AP. 

So I tested mdk3 standalone (without wifiphisher running in parallel) and found out that mdk3 will not only disconnect my Windows 10 Laptop. My Windows 10 Laptop will stay disconnected afterwards (will not connect back to the target AP automatically). I think that windows somehow marks that target AP unusable. This seems to be the reason why windows afterwards connects to the evil twin quite quickly, because the target AP is seen unusable or something like this.

I don't known what mdk3 exactly does, but from the traces one can say it not only send out bursts of deauth frames. Instead it constantly deauthenticate the client each time he reconnects to the network. Deauth frames are sent like this:

![screenshot from 2018-10-19 10-35-40](https://user-images.githubusercontent.com/44227524/47207288-2802ff00-d38b-11e8-9dfb-f36b2f95c8e4.png)

So all in all one can say, that running mdk3 in parallel to wifiphisher will provide a much more efficient and persistent interruption of the WiFi connection between Wifi Stations and the target AP. Maybe wifiphisher could benefit from that.

But still this issue can be closed as it seems to work as expected. Thanks for your great work :-)

**Comment by sophron** [comment]
Thank you. This analysis is very helpful.

> You are right, the deauthentication is done by wifiphisher as expected. I can see bursts of 10s deauthentication frames every 30s on the channel, which is used by the target AP and my test Laptop.

Hmmm, the deauthentication frames should not occur every 30 seconds. I believe this is because of the channel hopping. I pushed a commit that introduces a new option `--deauth-channels`. You can now specify the channels that you want to deauth for the hopping (for example, --deauth-channels 4, 6). This should be much more efficient.

> Still, when launching mdk3 in parallel to wifiphisher, the Test laptop disconnects from the target AP much quicker and afterwards connects to the rogue AP, even if the rogue AP has same signal level as the target AP.
So I tested mdk3 standalone (without wifiphisher running in parallel) and found out that mdk3 will not only disconnect my Windows 10 Laptop. My Windows 10 Laptop will stay disconnected afterwards (will not connect back to the target AP automatically). I think that windows somehow marks that target AP unusable. This seems to be the reason why windows afterwards connects to the evil twin quite quickly, because the target AP is seen unusable or something like this.

The reason may be the inefficient (for this specific case) channel hopping that we were performing. Can you try again using the new option `--deauth-channels`?

If you could also share the Wireshark dumps (when running mdk3 and when running Wifiphisher) that would be very useful!

**Comment by whitehat2810** [comment]
@sophron thanks, selecting the channel for deauthentication works much better (quicker). Still mdk3 seems to do something different as the client will not connect back to the AP when mdk3 is running. I sent you traces via Mail.
