### ISSUE TITLE
How i can add new fake pages

### ISSUE THREAD

**Issue by ImDoode** [wifiphisher/wifiphisher#1035]
Dublicat has no answer https://github.com/wifiphisher/wifiphisher/issues/402
How I can add new page or edit current pages? There is no changes

**Comment by zeeshan7860** [comment]
by using oauth-login scenario which is facebook phishing page when i write mobile number in the Email text field it does not except and say that wrong email or password and you know  some people make the facebook account on their cell number rather than email so it should accept the phone No. i also try to modify the index.html file no avail
