### ISSUE TITLE
Deauth and Rogue AP issues in Test Environment

### ISSUE THREAD

**Issue by z66z** [wifiphisher/wifiphisher#1078]
when I started wifiphisher
I can see wfphshr-wlan0 is created for deauth and wlan0 for rogue AP initially

**Testing scenario:**
There are 6 clients connected to the AP. The power wifi is at 96%. Dual Boot kali and Windows machine. Used Windows Laptop inbuilt wireless card for the process.

1 Mac OSX
2 iphone ios
3 xiaomi android
4 samsung android
5 Windows PC
6 IPAD

The deauth didn't work in none of the devices. All the devices are connected.

**Issue 1:** Deauth didn't work
**Issue 2:** In Mac OSX the Clone ESSID i.e the Rogue Access point created is shown as " TEST ". But it shows correctly in the rest.
**Issue 3:** In Xiaomi Android mobile the AP created by Rougue AP is not shown. If I disconnect from the existing wifi network, Then AP created by Rogue interface is shown.

**NOTE: DEAUTH works using aireply-ng.**

**Question1:** Cant I simultanesouly do Deauth attack using wfphshr-wlan0 and create a Rogue AP using wlan0 at the same time using one inbuilt wireless card in a laptop.
**Question2:** Is there a way that I can Deauth alone using aireplay-ng and rest of the process using wifiphisher using one inbuilt wireless card in a laptop?

I can attach screenshots If necessary.
Thanks

**Comment by sophron** [comment]
Hi and thanks for reporting.

> **Issue 1:** Deauth didn't work

Read the FAQ about this: https://wifiphisher.readthedocs.io/en/latest/faq.html#why-does-deauthentication-is-not-always-working

> **Issue 2:** In Mac OSX the Clone ESSID i.e the Rogue Access point created is shown as " TEST ". But it shows correctly in the rest.

The "TEST" that you are seeing is probably because of the KARMA attack. In other words, your Mac OSX machine had previously connected to a "TEST" network in the past. Wifiphisher exploits the "Auto-Connect" feature in this case. The ESSID of the cloned network should still be there though. Did you wait for at least a couple of minutes? It may take a while for your machine to scan the nearby WLANs.

> **Issue 3:** In Xiaomi Android mobile the AP created by Rougue AP is not shown. If I disconnect from the existing wifi network, Then AP created by Rogue interface is shown.

Again, are you sure you wait for at least a couple of minutes? It may take a while for the network to appear.

> **Question1:** Cant I simultanesouly do Deauth attack using wfphshr-wlan0 and create a Rogue AP using wlan0 at the same time using one inbuilt wireless card in a laptop.

Yes, if your card supports it. If you didn't receive any error messages, then your card does support it and you are probably doing it already. If it's not working as expected see my first answer.

>**Question2:** Is there a way that I can Deauth alone using aireplay-ng and rest of the process using wifiphisher using one inbuilt wireless card in a laptop?

Yes. You will have to create a different virtual interface for aireplay-ng. Then run Wifiphisher with `-nD` option to turn off deauthentication.
