### ISSUE TITLE
wifiphisher  ( The MAC address could not be set. (Tried 00:00:00:a4:8c:29) )

### ISSUE THREAD

**Issue by jbondye** [wifiphisher/wifiphisher#1151]
root@kali:~# cd wifiphisher
root@kali:~/wifiphisher# wifiphisher --force-hostapd
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-07-17 10:06
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:cc:63:fc
[!] The MAC address could not be set. (Tried 00:00:00:53:81:c9)
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Using hostapd instead of roguehostapd. Many significant features will be turned off.
[*] Starting the fake access point...
[!] hostapd failed to lunch!
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] The MAC address could not be set. (Tried 00:00:00:a4:8c:29)
[!] Closing

**Comment by sophron** [comment]
Read the README. You can turn off randomization with `--no-mac-randomization`.

**Comment by nowaynear** [comment]
root@kali:~/wifiphisher# wifiphisher --force-hostapd --no-mac-randomization
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-07-23 15:58
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Using hostapd instead of roguehostapd. Many significant features will be turned off.
[*] Starting the fake access point...
[!] hostapd failed to lunch!
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] The MAC address could not be set. (Tried ce:07:b4:ce:cc:15)
[!] Closing
root@kali:~/wifiphisher# 
please let me know its solution i tried many things but not working

**Comment by sophron** [comment]
Okay, looking at it again, it appears that hostapd failed to lunch. Try re-installing hostapd, e.g. "apt-get purge hostapd && apt-get install hostapd".

**Comment by sahdow3256** [comment]
Not work for me do you have another solution ?
