### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by mmm7761** [wifiphisher/wifiphisher#1346]
i did the first 2 cmds and by the last one (sudo python setup.py install)

it gives me this error:

Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from setuptools import Command, find_packages, setup
ImportError: No module named setuptools

im new to kali so forgive me if im just doing something wrong

**Comment by qbwza** [comment]
> did the first 2 cmds and by the last one (sudo

me too

**Comment by mmm7761** [comment]
any fix?

**Comment by JetseVerschuren** [comment]
Try `pip3 install setuptools`.

**Comment by d33p3r** [comment]
> Try `pip3 install setuptools`.

It doesn't help.

I did this:
``root@premium:~# pip3 -V``
pip 19.2.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

So I tried this:
``root@premium:~# pip3 install setuptools``
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (41.2.0)
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Well, I did this:
``root@premium:~/wifiphisher# python3.0 setup.py install``
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from setuptools import Command, find_packages, setup
ImportError: No module named setuptools

So I did:
``root@premium:~/wifiphisher# python3.8 setup.py install``
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from setuptools import Command, find_packages, setup
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

**Comment by mmm7761** [comment]
> Try `pip3 install setuptools`.

not working this is what it says

kali@kali:~$ sudo pip3 install setuptools
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (41.2.0)
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by d33p3r** [comment]
> > Try `pip3 install setuptools`.
> 
> not working this is what it says
> 
> kali@kali:~$ sudo pip3 install setuptools
> WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
> Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (41.2.0)
> WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
> Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Sorry, I can't solve this problem. Can anybody help me (and us)?

**Comment by samiabu123** [comment]
yah same i have the same problem

**Comment by JetseVerschuren** [comment]
First, that SSL warning is annoying, but it still stated that setuptools is installed. This means that you should be able to install wifiphisher using `python3 setup.py install`, make sure you have the latest version from Github (`git pull` should be enough) and you're using python version 3.
Second, I've never seen that SSL error. My best bet would be to install the ssl package using `apt install python3-openssl` or update your full system (`apt update && apt upgrade`)

**Comment by JetseVerschuren** [comment]
@d33p3r Look at [this stackoverflow answer](https://stackoverflow.com/a/53696838), it seems to solve a similar error.

**Comment by mmm7761** [comment]
> First, that SSL warning is annoying, but it still stated that setuptools is installed. This means that you should be able to install wifiphisher using `python3 setup.py install`, make sure you have the latest version from Github (`git pull` should be enough) and you're using python version 3.
> Second, I've never seen that SSL error. My best bet would be to install the ssl package using `apt install python3-openssl` or update your full system (`apt update && apt upgrade`)

none of those cms helped 

this one gave me a error tho


root@kali:/home/kali/wifiphisher# python3 setup.py install

/tmp/tmp_netlink__u4aefm5/test_netlink.c:2:10: fatal error: netlink/netlink.h: No such file or directory
    2 | #include <netlink/netlink.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev

**Comment by mmm7761** [comment]
ok i did these 2 cmds and it worked, thanks!!!

apt-get install libnl-3-dev libnl-genl-3-dev

apt-get install libssl-dev

**Comment by mmm7761** [comment]
nvm when i try to run it i get this

root@kali:/home/kali# wifiphisher


Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyric' distribution was not found and is required by wifiphisher
root@kali:/home/kali#

**Comment by mhmdnxsr** [comment]
root@kali:/home/mhmdnasr/wifiphisher# apt-get install setup.py
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package setup.py
E: Couldn't find any package by glob 'setup.py'
E: Couldn't find any package by regex 'setup.py'
any help ??

**Comment by d33p3r** [comment]
Ok guys, I found the solution. It's crazy, I know, but it's the only way which works for me anyway.

1. I threw away my old backtrack 5R3. **Wifiphisher** would not work on that system and I guess -
 it will not.
2. I downloaded the latest Kali 2020.2 and installed it on the hard disk: https://www.kali.org/downloads/
3. After long and succesfull installation I did: `sudo apt update && apt full-upgrade -y`
4. Then: `sudo apt-get install libnl-3-dev libnl-genl-3-dev`
5. Then: `sudo apt-get install libssl-dev`
6. Then: `sudo apt-get install libpcap-dev` (reaver needs this lib)
7.  I downloaded the latest version of **Wifiphisher** and installed as it is here: https://github.com/wifiphisher/wifiphisher/#installation
8. During the installation of **Wifiphisher** the internet connection must be ON, because program will be downloading some additional stuff.
9. Once again: `sudo apt update && apt full-upgrade -y`
10. Run the program as they describe: https://github.com/wifiphisher/wifiphisher/#usage

I had to run it 2 times, because at the first time it's just stopped...

**Wifiphisher** works fine for me.

**Comment by JetseVerschuren** [comment]
> root@kali:/home/mhmdnasr/wifiphisher# apt-get install setup.py
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package setup.py
> E: Couldn't find any package by glob 'setup.py'
> E: Couldn't find any package by regex 'setup.py'
> any help ??

`setup.py` is a python file, you need to run it using `python3 setup.py install`. See the README for more details.

**Comment by Rombersoft** [comment]
Can I install it on Debian 10? I have the same problem and your solutions do not help
