### ISSUE TITLE
"OAuth Login Page" scenario does not work fine

### ISSUE THREAD

**Issue by secuhiro** [wifiphisher/wifiphisher#1392]
I started wifiphisher and choose my AP.
Then I selected "OAuth Login Page" for the senarios.
After that, I selected my AP from my mobile(192.168.1.7), but connection failed(come up "Authentication error" on my mobile screen ).
When wifiphisher is not runnning, No problem to connect from my mobile to the AP though.
I may make some misunderstanding. So Please point out what's wrong with me.

![2020-11-02_17h00_15](https://user-images.githubusercontent.com/73603024/97844053-ad1c9f00-1d2d-11eb-8be4-0c51a989b980.png)

![2020-11-02_17h01_35](https://user-images.githubusercontent.com/73603024/97844460-67140b00-1d2e-11eb-8bb1-56386112ab70.png)

![2020-11-02_16h51_20](https://user-images.githubusercontent.com/73603024/97844477-709d7300-1d2e-11eb-836f-660450d394dc.png)

**Comment by kazak01xd** [comment]
So let's walk step by step on the attack. You first launch wifiphisher and then allow it to scan for WiFi APs around you while its under monitor mode, then you select the one you want to attach using the arrows and hit enter, then after that you it takes you to the next page where it asks you what type of attack you want to launch and you select number 4 and hit enter. From that point the expected behaviour should be that wifiphisher launches the fake evil twin AP that the victim will connect too and then wifiphisher will also start a deauth attack to disconnect the victim(s) from the target AP. at that point are you having difficulty connecting to the evil twin AP? is that what I'm understanding? with you mobile? have you tried any other devices? or a different attack?

**Comment by secuhiro** [comment]
Please excuse my lack of explanation. 

>You first launch wifiphisher and then allow it to scan for WiFi APs around you while its under monitor mode, 
>then you select the one you want to attach using the arrows and hit enter,
>then after that you it takes you to the next page where it asks you 
>what type of attack you want to launch and you select number 4 and hit enter.
So far Yes.

My AP at home network  I choosed was HG8045-CEF-bg(192.168.1.1). My understanding is this AP would be fake AP.
So I connected to this AP from my mobile(192.168.1.7) and my desktop which is installed kali linux including wifiphisher on virtual box in Win 10(192.168.1.2)

**Comment by kazak01xd** [comment]
> Please excuse my lack of explanation.
> 
> > You first launch wifiphisher and then allow it to scan for WiFi APs around you while its under monitor mode,
> > then you select the one you want to attach using the arrows and hit enter,
> > then after that you it takes you to the next page where it asks you
> > what type of attack you want to launch and you select number 4 and hit enter.
> > So far Yes.
> 
> My AP at home network I choosed was HG8045-CEF-bg(192.168.1.1). My understanding is this AP would be fake AP.
> So I connected to this AP from my mobile(192.168.1.7) and my desktop which is installed kali linux including wifiphisher on virtual box in Win 10(192.168.1.2)

Yeah so it seems like your having trouble connecting to your Evil Twin AP right? have you tried launching it against a different network (only temporarily) and tried connecting to a the evil twin wifiphisher will spawn in order to rule out your cellphone as the problem. it shouldn't have a problem. also try using a different option instead of number 4 it could be an issue with that. let me know how that works and get back to me if it doesn't solve the issue. on my integrated laptop wifi card I'm able to get it to work although the range of the attack wont be very far. if you could also record your screen and upload it to youtube if you have a channel that would be cool to not only help solve your problem but also get more people interested in wifiphisher.

**Comment by secuhiro** [comment]
Thank you for your advice always.

Yes, I will try to upload to youtube even I dont have channel yet. It is good to understand more for me as well.
Before I try to another scenario, let me doublecheck about senario 4

My understanding about senario 4 is that
Step1:  launch wifiphisher
Step2:  select the AP  (I selected the AP_192.168.1.1 which is my home rooter in my case)
Step3:  select senario 4
Step4:  connect to AP form some devices ( I connected 192.168.1.1 from my cellphone_192.168.1.7 or desktop_192.168.1.2)
Through these steps, finally a fake authentication page(like facebook?) will come up on the cellphone screen / desktop monitor.

**Comment by kazak01xd** [comment]
> Thank you for your advice always.
> 
> Yes, I will try to upload to youtube even I dont have channel yet. It is good to understand more for me as well.
> Before I try to another scenario, let me doublecheck about senario 4
> 
> My understanding about senario 4 is that
> Step1: launch wifiphisher
> Step2: select the AP (I selected the AP_192.168.1.1 which is my home rooter in my case)
> Step3: select senario 4
> Step4: connect to AP form some devices ( I connected 192.168.1.1 from my cellphone_192.168.1.7 or desktop_192.168.1.2)
> Through these steps, finally a fake authentication page(like facebook?) will come up on the cellphone screen / desktop monitor.

So make sure you're connecting to the fake AP that is unlocked. thats the AP that the victims will have to connect too. it will not allow you to connect to the real locked AP because of the deauth attack. upload the video and share the link here. I will try and see what the issue is; if we cant solve it with that maybe if you have discord I can try and help you over that to solve the issue.

**Comment by secuhiro** [comment]
I am afraid that I may misunderstand senario4.
So sorry for bothering you many time but let me doublecheck once more

My understanding about senario 4 is that
Step1: launch wifiphisher
Step2: select the AP (I selected the AP_192.168.1.1 which is my home rooter in my case)
Step3: select senario 4
Step4: connect to AP form some devices ( I connected 192.168.1.1 from my cellphone_192.168.1.7 or desktop_192.168.1.2)
Through these steps, finally a fake authentication page(fake facebook login page) will come up on the cellphone screen / desktop monitor.

My understanding is correct or not?

**Comment by rajairfan78** [comment]
I have also a little problem related to this !
When i do wifi phishing attack and client connects to my Fake AP, it doesn't redirect it to the fake login page. Why?

**Comment by kazak01xd** [comment]
> I am afraid that I may misunderstand senario4.
> So sorry for bothering you many time but let me doublecheck once more
> 
> My understanding about senario 4 is that
> Step1: launch wifiphisher
> Step2: select the AP (I selected the AP_192.168.1.1 which is my home rooter in my case)
> Step3: select senario 4
> Step4: connect to AP form some devices ( I connected 192.168.1.1 from my cellphone_192.168.1.7 or desktop_192.168.1.2)
> Through these steps, finally a fake authentication page(fake facebook login page) will come up on the cellphone screen / desktop monitor.
> 
> My understanding is correct or not?

I just want to be sure that your selecting the fake AP and not the AP your attacking. This tool it suppose to attack a wifi access point and by doing so disconnect all wifi connected devices from it. THEN the OTHER evil twin wifi AP will appear without a password set too it. the theory is that the victims will assume something is wrong and connect to the fake evil twin one and be redirected to a captive portal that will ask them for passwords. I just want to be sure your not misunderstanding the actual purpose of this tool. that's why I wanted you too make a video to make sure your following the process along.

**Comment by kazak01xd** [comment]
> I have also a little problem related to this !
> When i do wifi phishing attack and client connects to my Fake AP, it doesn't redirect it to the fake login page. Why?

that sounds more like an actual issue with either the code that prompts new connected devices into the captive portal. when you connect try and browse the internet and see if when it does it force redirects you to the captive portal page. if not then we have a a bug that needs to be alerted on.

**Comment by ebrahimshanu2010** [comment]
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-12-06 04:47
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0mon interface for the deauthentication attack
[+] Selecting wlp2s0 interface for creating the rogue Access Point
[+] Changing wlp2s0 MAC addr (BSSID) to 00:00:00:61:3b:c8
[+] Changing wlp2s0 MAC addr (BSSID) to 00:00:00:2a:4a:e4
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to NetworkManager
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
Segmentation fault (core dumped)

**Comment by sophron** [comment]
Hi guys,

I pushed a commit yesterday that fixes this. Please update to the latest revision and try again.
