### ISSUE TITLE
Log all data in a separate file 

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#427]
The feature to log all data in a separate file could be very useful for those who run Wifiphisher for a long time and also for debugging.

**Comment by alexsalvetti** [comment]
Hi, maybe in the next days I'll work on this since I had made a PR of a logger time ago.. #260

**Comment by sophron** [comment]
That's great @alexsalvetti! For now I want to be able to do the following:

(Assuming an `output` object from an `Output` class that is responsible for printing information to screen and logging to files)

`output.send(data, type="INFO", stdout=True, file=True)`

The above should print the data to screen and store them to the file, while 

`output.send(data, type="INFO", stdout=True, filesystem=False)` 

should only print this information to the screen and not log it in the filesystem.

For storing the data to files, I recommend using Python's <a href="https://www.blog.pythonlibrary.org/2012/08/02/python-101-an-intro-to-logging/">logging library</a>.

So, the code would look like this:

```Python
class Output:
  def send(data, type, stdout=True, filesystem=True):
    if stdout:
      if type == "INFO":
        print "[*]" + data
      elif type == "WARNING":
        Print "[!]" + data
       ...
    if filesystem:
      if type == "INFO":
        logging.info(data)
      elif type == "WARNING":
        logging.warning(data)
    ...
```

Something like that. Lemme know if any questions.

**Comment by alexsalvetti** [comment]
Perfect @sophron! What you wrote here was my same idea... Indeed I was reading this: https://docs.python.org/2.7/howto/logging.html 

I'll start working on this after exam session ends.. :wink:

**Comment by sophron** [comment]
Sounds great. :)

**Comment by mojave-doug-f** [comment]
Has this feature been implemented yet?

**Comment by alexsalvetti** [comment]
No it's not being implemented from me because I have no time at the moment.

**Comment by laozi999** [comment]
I'll finish [this](https://github.com/wifiphisher/wifiphisher/issues/537)

**Comment by mojave-doug-f** [comment]
Roger that :)

This will be great when it is finished. This will let me leave a Raspberry Pi in my bag and let wifiphisher run without being noticed. 

Having it out at a coffee show with a large wifi USB adapter and code scrolling across the screen is rather conspicuous. =P

**Comment by mojave-doug-f** [comment]
@laozi999 let me know if you need help testing.

**Comment by formica45** [comment]
Some kind of logging is crucial for this. I don't have the time to sit an watch. 

Great job on this. Been looking for a consistently working "wifi phisher" for awhile now. This is simple and to the point. Hope it doesn't bloat into useless.

**Comment by blackHatMonkey** [comment]
@sophron I was going to work on the logging and wondering where should we log? Perhaps `/tmp` would be the best option.

**Comment by sophron** [comment]
@blackHatMonkey Great!

We should not log in a file by default. Users that want to have a Wifiphisher session logged, should use an `-oN` or `--output-normal` and then a filename argument (see Nmap's <a href="https://nmap.org/book/output-formats-normal-output.html">-oN</a>. The log file should be saved in the current working directory.

**Comment by blackHatMonkey** [comment]
@sophron I'm still not sure if we should log by default or not. On one hand we have ease of use and on the other hand we have more control.

That problem aside I'm currently working on it and we should agree on a format of log file. For instance we can have this:
```
Time - Level - Message
2017-08-21 10:39:45,942 - INFO - A new client is found
```
or we can have something like this:
```
Time - Module - Level - Message
2017-08-21 10:39:45,942 - Wifiphisher.Deauth - INFO - A new client is found
```
or any combination of [these](https://docs.python.org/2/library/logging.html#logrecord-attributes) flags. 

Also I think we should have a file rotator so that it creates a new file each time you run it (up to a certain amount). For instance if we set to maximum backup to 3 it would look something like this.
```
$ ls
wifiphisher.log     wifiphisher.log.1     wifiphisher.log.2     wifiphisher.log.3
```

**Comment by sophron** [comment]
>@sophron I'm still not sure if we should log by default or not. On one hand we have ease of use and on the other hand we have more control.

As I stated earlier, I think we should not log by default. A Wifiphisher session may run for days (e.g. under a Raspberry Pi hidden in the target's ingfrastructure) and the logs may get too big.

>That problem aside I'm currently working on it and we should agree on a format of log file.

I like the second one with the only difference that the microseconds seem unnecessary. "2017-08-21 10:39:45 - Wifiphisher.Deauth - INFO - A new client is found" looks good.

>Also I think we should have a file rotator so that it creates a new file each time you run it (up to a certain amount). For instance if we set to maximum backup to 3 it would look something like this.

Instead of a file rotator, I suggest naming each log file using a timestamp (i.e. `wifiphisher-session-20170821453910`) See how I did it for Lure10.

**Comment by yungtravla** [comment]
I've been working on a logger module. It's mainly inspired by [BetterCAP](https://github.com/evilsocket/bettercap) & [this](https://github.com/wifiphisher/wifiphisher/issues/537).

It allows for ...
- different log types ([i], [w], [d]) (info, warning, debug)
- toggling log types on/off
- clear and consistently structured logs with color coding
- option to enable timestamps
- option to save logs


I'm also working on something for the captive portal handler so that, when specifying `-p` (a phishing scenario), it will add the client's DHCP lease to another temporary log file after they successfully submit a 'wfphshr-' form in order to forward their requests to the internet (as suggested [here](https://github.com/wifiphisher/wifiphisher/issues/537) as well).


This would make a WPA phishing attempt very persistent. A 'router update' would indeed re-establish the internet connection immediately after a password is entered, which would seem more legit.

I've also allowed the user to skip the scenario selection stage if the `-iI` option is specified. It'll be easier to remotely initiate a Wifiphisher session from a command line in case one forgets to specify `-p` in order to skip the scenario selection menu.

**Comment by yungtravla** [comment]
Another good feature would be to remember hostnames for MAC, that way we can make more detailed logs. This would of course need to be able to detect when someone has either changed their hostname, or someone is using the same MAC as another device on the same network.

**Comment by yungtravla** [comment]
I think it would also be a good idea to change `-hC packet.pcap` to `-vH, --verify-handshake packet.pcap` and then add a new option called `-cH, --capture-handshake` to make Wifiphisher automatically capture a handshake from the selected AP.

**Comment by anakin1028** [comment]
@yungtravla we have discussed this in #661.
The reason why we force users to apply the capture is that four-way handshake proceeds very quickly, and it seems not possible to sniff all the four frames in our program.

**Comment by yungtravla** [comment]
@anakin1028 a deauthentication attack before spawning a rogue ap will cause the victim to re-establish a handshake with their trusted network they got disconnected from. It is very simple and quick to capture a handshake before starting the attack.

If no one is on the network to capture a handshake from, you might as well wait instead of broadcasting an evil AP for no reason.

**Comment by yungtravla** [comment]
And it looks like that would fully legitimize the WPA password capturing process. It can always check to confirm whether the password is correct or not, throw the error like you did [here](https://github.com/wifiphisher/wifiphisher/pull/661) as if it was their very own router.

**Comment by yungtravla** [comment]
Seems like you already did most of the job @anakin1028 !

> The current deauth module deauth too fast. The deauth process will make the victim not complete the four way handshake. Maybe we can improve the deauthing process in the later PR.

This should fairly simple to fix.

**Comment by anakin1028** [comment]
@yungtravla 
 * The comment above is one reason.
 * The other one is the main reason:
    To calculate the MIC from the passphrase we need to capture all four frames in four-way handshake. The problem of our current framework is we cannot sniff all four frame in one-shot. Though we may use deauthentication to cause the victims do the association again, we still cannot sniff all four frames (i.e. There are too many frames on the air). 

For example we may sniff the frames like the following:
```
EAPOL-MSG1
BEACON (loss msg2)
BEACON (loss msg3)
EAPOL-MSG4
```
Then we cannot calculate the MIC from this capture.

You may think we can continuously to sniff until all four frames are collected. However, notice that the S-NONCE and AP-NONCE will be changed under different fourway handshake.

**Comment by yungtravla** [comment]
@anakin1028 

Please explain to me why I am able to capture a 4-way handshake with only 1 deauth packet using airmon-ng and aireplay-ng, and not with wifiphisher?

**Comment by anakin1028** [comment]
@yungtravla 

`airmon-ng` uses all the resource to sniff frames (i.e. just like you lunch wireshark and continuously sniff on the air), but for `wifiphisher` we have to do other things.

When sniff one frame we'll process that frame and during the process time, we don't continuously sniff the frames on the air. You can see the `count=1` on the following code. 
```python
while self._should_continue:
            dot11.sniff(
                iface=self._interface,
                prn=self._process_packet,
                count=1,
                store=0,
                stop_filter=self._stopfilter)
```
If we really want to implement on-fly capture, we need to dedicate one process to sniff the EAPOLs. This is the only solution I can think for now.

**Comment by yungtravla** [comment]
You're right, packets have to be added to a queue and individually parsed, we shouldn't be using spaghetti code that holds up the process.

**Comment by blackHatMonkey** [comment]
The #747 is in the progress and should be done soon.

**Comment by blackHatMonkey** [comment]
#747 Has implemented this feature.
