### ISSUE TITLE
Update wifi_connect template to support Android/iOS devices

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#435]
@dionyziz has done a great job with `wifi_connect` template that currently supports Windows & Mac OS network managers.

We should extend it even more and support Android & IOS network managers too. For example, a victim that runs Android should see something like the image below:

![iiattachlink](https://cloud.githubusercontent.com/assets/554314/22624203/cdaa0b68-eb7c-11e6-8245-c73339c93894.png)

**Comment by mcocigra** [comment]
Not a bad idea but first the fix for jamming because without that this is useless

**Comment by cicina** [comment]
When is this update released? Sounds very good.

**Comment by cicina** [comment]
@mcocigra 

Temporarily, you can use aireplay-ng for hardcore deauth with --nojamming option, see earier topic

**Comment by mcocigra** [comment]
@cicina

Just opened a new issue for the no jamming to see what is best to use and which commands. If you could reply there would appreciate it . Thanks

**Comment by alexsalvetti** [comment]
For ios it's simple because if people have ios from 7 up to 10 the alert is the same as this one: 
![cattura](https://cloud.githubusercontent.com/assets/7389032/22778807/818f6590-eeb8-11e6-8803-3cfb08f7d70d.PNG)

For android I was thinking to use javascript prompt alert and hide the tilte for not having the "The page www.---.com says:"

**Comment by mcocigra** [comment]
@alexsalvetti  this look REALLY fake to me I don't think anyone will go for it.
The picture that @sophron has posted is much more believable.
This is how asking for password looks like on my phone.
Maybe more people should post images and we should make it look more genuine.
![screenshot_2017-02-09-15-52-49](https://cloud.githubusercontent.com/assets/25259626/22788536/62f9dfc0-eee0-11e6-9241-6f23ac616276.png)
And a screenshot with the advanced options. I am on android 6.0 Huawei phone emi 4.1
![screenshot_2017-02-09-15-58-44](https://cloud.githubusercontent.com/assets/25259626/22788611/b34a42d0-eee0-11e6-9e13-aefe5ae8a9a8.png)

**Comment by alexsalvetti** [comment]
As I said @mcocigra on Android there's plenty of different UI based on version of Android and the the Vendor UI.. so we have also plenty of different "Password asking" pop-ups.. 
As this wifi_connect page may result as fake to a "expert" look, I think that a javascrpit pop-up will look inoffensive to normal people. 
I've already tested this javascript pop-up method on my android phone and on my iphone and it doesn't look that bad..

**Comment by cicina** [comment]
I like the last one :) 

yeah, every android use different style, mine is Vibe UI and looks totally different from your huawei. and its still android 6..

**Comment by mcocigra** [comment]
If we are talking about more believable the first one from @sophron is the best it need a little tweaks but still is good. For the last one from @alexsalvetti it needs complete redesign. We are trying to make it look like you have been disconnected and are trying to connect again from the system not like the web page is asking for a password. Like this everyone will think is some kind of an ad or one of those annoying pop up ads with viruses and will just press the back button to dismiss it. Every ui is different but still has similarities like encryption, signal strength , the advanced options , some sort of show password button and others.

**Comment by alexsalvetti** [comment]
You are talking about the "credibility" of @sophron image but, if you see, that's a screenshot of the system pop up that shows up when you connect to a network on a samsung device.. 
So there no coding behind that image.. I think that since this is an open source code you can develop the pop up that fits your expectations and use it on your own or share it.. I personally prefer fast but effective solutions. 
Peace out.

**Comment by mcocigra** [comment]
We all want that but not everyone is a developer and able to make their own templates and designs. It should be a complete solution not half way or not even half.

**Comment by sophron** [comment]
@alexsalvetti I like the JS popup. If you make a PR that includes this to "wifi_connect" template, I will happily merge it.

**Comment by sophron** [comment]
@mcocigra This is an open-source project and noone is getting payed. The best one can offer is always welcome :)

**Comment by mcocigra** [comment]
@sophron  I know just trying to help that's why I posted screenshots of my interface of connecting.Yes the functionality is good if it pops up and works. Just the design was my remark. One question can we make it pop up anywhere not only in the browser but in some apps like Facebook app or viber or anything that asks for internet connection. That would be very effective.

**Comment by cicina** [comment]
@mcocigra im afraid thats not possible... how do you mean that anyway? You would need to hack device, create modified facebook app, install remote on victim device and wait for him to run it? I dont think so.

**Comment by alexsalvetti** [comment]
@mcocigra I would not spend any other time here replying to some impossible ideas.. everybody's got good ideas but first you should imagine if they are possible or not.. to make those supposition you gotta have some basic understanding of how those things works. I'm not the expert of the situation here and certainly @sophron is the right one.
ASAP I'll make a PR of the JS pop up.

**Comment by mcocigra** [comment]
Know it was a long shot just fantasizing. How great it would be if it was
