### ISSUE TITLE
Solution for the no jamming issue

### ISSUE THREAD

**Issue by mcocigra** [wifiphisher/wifiphisher#437]
For the best solution it will probably be using mdk3 and the no jamming option. Mdk3 because like I have read it will jamm the victim even if it changes channels and the no jamming option in wifiphisher for the fake network.
What will be the best commands to use and with what interface

**Comment by blackHatMonkey** [comment]
I have already written the code for the re-designed jamming. It is currently in testing phase and should be pushed out in a couple weeks or so.

**Comment by cicina** [comment]
If aireplay-ng won't run because of channel, you also might want to put your card in specific channel, use first command with channel number like:  `airodump-ng start wlan0 X`
where "X" is channel number of AP u want to attack. I dont know why but this is not necessary most of the time. For me this steps are working and deauth is aggressive enough and I dont need to change channel for my wifi card usually.

**Comment by mcocigra** [comment]
@blackHatMonkey
This is a temporary solution. But for the jamming it would be nice to implement jamming on all the channels or the victim should be monitored and the channel should change automatically because after a while I have observed that tha victim changes channels and in the program nothing happens it continues to work like nothing is wrong but it actually isn't doing anything. And for the output in the jamming part and the leasing part it should REFRESH because I have noticed that if one of the clients that is jammed turns off internet it is still in the list and if one of the clients that is leasing from the fake network disconnects it is still in the list. This is very confusing we have the impression that everything works but it actually isn't doing anything.

**Comment by mcocigra** [comment]
@cicina
Will read a little because I am not very good with commands. Will try it out and report is it working. From my understand of things so far I think mdk3 is a better solution because it deauthanticates everything from the client on every channel. And I will check if people connect to the fake network

**Comment by cicina** [comment]
What channels are you talking about? Correct me if I am wrong, but there is only AP channel, which could be changed maybe even with every router restart. What do you mean by "it deauthanticates everything from the client on every channel" - its what both tools do. AP could have only one channel at time. 

Well, you can use mdk3 if you prefer, basically same thing, start wifiphisher with option I mentioned earlier, and run mdk3 instead of aireplay-ng. But my script makes break for 10 second and send only 30 or 20 deauth packets, If you are going to run mdk3 you will need to stop and start script manually which could be annoying. You can't just DOS them all day.

**Comment by mcocigra** [comment]
@cicina
Yes on the deauthentication all the time so they think they don't have internet and hopefully connect to the fake network. And about the channel was thinking on the channel of the router you are attacking if it changes channel doesn't mdk3 continue to attack it no matter on which channel it is and doesn't mdk3 attack the router and the clients connected to it or only the router

**Comment by cicina** [comment]
oh, okay, then we are talking about router channel. anyway, in command `airodump-ng -c 1 --bssid 00:11:22:33:44:55 wlan0mon` you are basically telling airodump which channel to use. anyway, I cant see relevant reasons not to use aircrack because of this. Router channel does not change every 5 seconds, only if victim change channel or if router is configured to do so after reboot. Anyway you will still see that channel in `airodump-ng wlan0mon`.. so yeah.. up to you mate. 

If you still want to use aireplay-ng for deauth and want to do permanent DOS, dont use script (as this script is useful only if you DONT want to attack router permanently but with breaks) and simply use 
`aireplay-ng -0 0 -a 78:96:82:7a:8f:71 wlan0mon`

In case you are going to use mdk3, you could post results here just for my curiosity as I haven't done dos with mdk3 yet :)

**Comment by mcocigra** [comment]
@cicina
Thanks a lot hopefully will get it to work try it and post results. On a side note I used wifiphisher a few months ago with the first scenario when it was just a box looking for wpa password and it worked perfectly and that time was also mobile friendly. Let's see if this works if not hopefully the update and upgrade of wifiphisher comes soon and works.

**Comment by cicina** [comment]
Yeah remember - white page with shiny red style, simple and useful. I would love to see this old scenario back again.

**Comment by sophron** [comment]
@mcocigra, I understand that you want the tool to be more effective when it comes to de-authentication. We are currently working on it. However, commenting about the same thing on different threads, won't speed-up the process. If you want to use `mdk3` or any other alternative and need advice, please post on the relevant forums.

I also don't understand which scenario you and @cicina are talking about. Which one is the one that you miss?

**Comment by cicina** [comment]
@sophron I am talking about this one: http://www.wirelesshack.org/wp-content/uploads/2015/01/Wifiphisher-new-wireless-router-attack.png is there any change to add this one to the list? I know its now replaced by new router upgrade but this could be included as well

**Comment by mcocigra** [comment]
@sophron
Sorry didn't try to be annoying. I was talking about it on another thread but only a few sentences nothing specific. I opened this one so that if we found a solution it will be visible to everybody. I don't  prefer using anything else I loved wifipfisher the last time I used it worked perfectly. And it's not about the effectiveness it's that is isn't actually working. And a big optimization would be if the lists refreshed. The jamming and the leasing lists I have noticed that if a device connects and disconnects it is still in the list. Thanks and again just trying to help

**Comment by mcocigra** [comment]
And another thing on the second scenario the only one mobile friendly when it asks for password the phrase use is " pre shared key" for anyone that doesn't live in a English spoken country would be very difficult to understand just write PASSWORD we are attacking the technologicaly challenged people not the advanced users

**Comment by mcocigra** [comment]
Have been trying with airplay-ng will post for results

**Comment by cicina** [comment]
@mcocigra hey mate just open that html file template and put "password" instead of "pre shared key"

**Comment by sophron** [comment]
@cicina In what aspect do you think that this template was more legit? 

You can still use it, by downloading an older version (e.g. v1.1) and then import to the current functionality (see the docs for more info on how to create a scenario).

@cicina You can try one of the <a href="https://github.com/sophron/wifiphisher/releases">stable releases</a>.

**Comment by sophron** [comment]
@mcocigra You can try one of the <a href="https://github.com/sophron/wifiphisher/releases">stable releases</a>.

**Comment by mcocigra** [comment]
Will try those too I tried the aireplay and with no jamming and I think this works but on the output is something wrong opened new issue. Hopefully things get sorted soon and really hoping for the new wifi connect template for mobile devices.

**Comment by mcocigra** [comment]
Just confirmed it the aireplay definitely works and the no jamming and fake network works it just isn't effective on everything mostly on android devices and the design needs some work it is very difficult to make people write the password

**Comment by blackHatMonkey** [comment]
#442 has been merged. The deauthentication should work properly now :smile:.

**Comment by cicina** [comment]
Deauth works thank you very much for fix :P you are awesome guys well done.

**Comment by blackHatMonkey** [comment]
Thats great to hear :smile_cat:.

**Comment by mcocigra** [comment]
Will test it out and report back

**Comment by sophron** [comment]
I just pushed more improvements to the deauthentication process. Let me know how you find them.

**Comment by mcocigra** [comment]
@sophron yes deauthentication now works I just think that it is jamming every client on every network it just shows to many. Haven't been able to test it to much  if not aireplay works good. I know there is no way to make them connect to the fake network if we could do something about it that would be useful and I have hi hopes about the network manager scenario

**Comment by mcocigra** [comment]
@sophron works great jamming every client now just the design should be improved a little remark on the second scenario it should be able to write a password without ticking the box and pre shared key should be changed to password and maybe implement some more logos of routers there isn't a zte one and some others are missing as well. And for the first scenario make it look like more of a system pop up than a page pop up put fields like signal strength and encryption type so it looks more like a pop up from android.
