### ISSUE TITLE
Mimic MDK3's deauthentication

### ISSUE THREAD

**Issue by Emberborne** [wifiphisher/wifiphisher#560]
This will probably not be on the top of your priority list, but it would be cool if you would 'Destroy' the real victim's ap with an mdk3 attack. Imagine the router reboots, then the victim will be completely forced to join the fake WP ap. This is really for resilient victims, those who didn't get tricked in the first place.

**Comment by sophron** [comment]
Hi @Emberborne,

`mdk3` mounts a number of different attacks for different scenarios. Which one you have in mind? (We already mount a DEAUTH attack against the target AP)

**Comment by laozi999** [comment]
Lots of new routers are protected against these DoS attacks.

I think you'd need multiple interfaces with a strong signal, combined with constant spoofing in order to make these attacks have any effect.

**Comment by blackHatMonkey** [comment]
After a discussion with @sophron we came to the conclusion that we to mimic `mdk3`'s deauthentication and we need to know what `mdk3` is sending. So if anyone can help that would be great.

**Comment by anakin1028** [comment]
I have tried the mdk3 deauthentication attack, the attack not only sends the deauth frame but also disassociated frame. The command I executed is as follow: 
 `mdk3 mon0 d -c 1` 

The frame injection pattern is like the following state diagram [I have removed the wds case, since wifiphisher only considers from DS and to DS cases]:

![mdk3_deauth](https://cloud.githubusercontent.com/assets/6182530/25116772/6400ee86-2441-11e7-8a49-c0ff940c50dd.png)

The following is the capture from wireshark:
In this example mdk3 listened one toDS frame [from Intel MAC to ASUS MAC]
Then it generates four frames following the above state transition diagram.

![mdk3_sniff](https://cloud.githubusercontent.com/assets/6182530/25117668/993ccd3c-2445-11e7-8524-ff65bf3c1c4d.gif)

Hope these information are useful for you.

**Comment by anakin1028** [comment]
Hi @blackHatMonkey,
Got another question for the deauth attack issued by wifiphisher:

The following is the snapshot from the mdk3 deauth attack:
![mdk3_deauth_frame_bssid](https://cloud.githubusercontent.com/assets/6182530/25159262/2d4a8b5e-24e1-11e7-8ab6-15218b744de2.png)

From the above figure you can see that the bssid of the deauth frames always equals to the MAC address of the access point, and from the 802.11 spec view, this is the correct way to implement.

The following is the deauth attack from wifiphisher:
![wifiphisher_deauth](https://cloud.githubusercontent.com/assets/6182530/25159329/ba1fefa6-24e1-11e7-97ae-66405f639766.png)

from the above figure, you can see the bssid is set as the sender's MAC address[i.e. address 2 of mac frame]

Is this intentional or just a mistake? I think this is the only difference between the deauth sent from mdk3
and wifiphisher.

Thanks

**Comment by sophron** [comment]
>I have tried the mdk3 deauthentication attack, the attack not only sends the deauth frame but also disassociated frame. The command I executed is as follow:

Correct. We should broadcast dissassociation frames as well.

>from the above figure, you can see the bssid is set as the sender's MAC address[i.e. address 2 of mac frame] Is this intentional or just a mistake? I think this is the only difference between the deauth sent from mdk3 and wifiphisher.

This is intentional. According to 802.11 an AP may send a Deauth frame to clients (i.e. when the router reboots). The client (or station) may send a Deauth frame too in some cases (i.e. when the station is leaving the BSS).

In our attack we craft three kind of deauth frames: 1 from the AP to the client, 1 from the AP to the broadcast address and 1 from the client to the AP. 

@anakin1028 Thank you for posting these. They are all useful.

**Comment by anakin1028** [comment]
@sophron, you're welcome
 
I know that wifiphisher will send deauth frames with sender equal to AP and STA; **however
the problem is that the address 3 should be fixed to bssid address.**  That is only interchanged with address 1 and address 2, but the address 3 is fixed to BSSID.

As the figures I post on the previous comment, you can see that mdk3 also sends the deauth frames with senders are interchanged, but the bssid[address 3] is fixed to the AP's MAC address.

The following is the table from 802.11 spec:
![tofromds](https://cloud.githubusercontent.com/assets/6182530/25169788/e7023568-251a-11e7-9b20-63639457cc84.png)

**Comment by blackHatMonkey** [comment]
@anakin1028 This is the code for crafting packets:
```python
 packet = (dot11.RadioTap() / dot11.Dot11(type=0, subtype=12, \
                    addr1=receiver, addr2=sender, addr3=sender) \
/ dot11.Dot11Deauth())
```
If you notice the `addr3` is set to the sender. Shouldn't that be the case?

**Comment by anakin1028** [comment]
@blackHatMonkey ,
I have seen that code, and addr3 should not set to the sender's address.
address3 should always be AP's MAC address for the fromDS and ToDS cases.

For example, 
-->consider STA sends the deauth to AP, then we have the following mapping:
      address1 = receiver's address = AP's MAC address
      address2 = sender's address = STA's MAC address
      address3 = BSSID = AP's MAC address = address1
-->consider AP sends the deauth to STA, then we have the following mapping:
     address1 = receiver's address = STA's address
     address2 = sender's address = AP's address
     address3 = BSSID = AP's MAC address = address2

So depends on fromDS or toDS cases, the address3 maybe mapping to address1 or address2

**Comment by sophron** [comment]
Good catch @anakin1028!

Do you think you can create a PR? I will happilly merge it. Maybe you can introduce "Disassociate" Frames as well?

**Comment by blackHatMonkey** [comment]
@sophron I can do a quick fix for the deauthentication. I think just renaming the input variables to `client` and `access_point` would solve the problem.

**Comment by sophron** [comment]
Thanks for offering Brian. I always prefer seeing new people contributing (the more in an open-source project the merrier). 

If however @anakin1028 is too busy to make the contribution, you can go ahead and implement it for us.

**Comment by anakin1028** [comment]
@sophron and @blackHatMonkey, I can help introduce the Disassociate frames.
So now the -jwlan# command will send the deauth frame and disassoc frame, or you prefer to do another option for users?

**Comment by anakin1028** [comment]
@sophron, 

Actually I dont't know why this command is useful:
`wifiphisher -aI wlan0 -jI wlan4 -p firmware-upgrade`

Though the stations will be deauthenticated by jamming deauths, the station will not connect wifiphisher's rogue AP since the rogue AP is OPEN, the original AP is CCMP encrypted. After deauthed station sends the probe request to rogue AP, it will get probe response, then it knows that the security information element is not fit, so victim station will never try to connect our rogue AP.

I think the only way to be useful, is original AP being reboot, which triggers users self manually connect our rogue AP, right?

**Comment by JetseVerschuren** [comment]
No strangely enough most clients don't check for the type of encryption.

**Comment by sophron** [comment]
Hi guys,

Automatic association will happen in some cases:

* When the target AP is OPEN. Our rogue AP is also OPEN, it can be part of the ESS and the STA won't notice any difference.

* When the target AP is WPA2 and our rogue AP is also WPA2 with the correct PSK (supplied with --presharedkey option). Same as above the STA will think our AP is part of the ESS.

* By exploiting the "Auto-connect" and "Available to all system users". For example, if I know an OPEN WLAN that the victim user has connected to in the past (or I can make an assumption), I can broadcast the exact same ESSID (with the --essid option) and assuming victim has the "Auto-Connect" flag enabled by default, the victim will automatically associate with our rogue AP. Adding a WLAN physically to the victim's device PNL (<a href="http://www.mathyvanhoef.com/2017/02/windows-10-lock-screen-abusing-network.html">here</a>) also belongs to this category.

* By mounting the Lure10 attack. This works on Windows10 / Windows Phone 8.1 and I recently gave a presentation about this. Check the slides <a href="https://census-labs.com/media/lure10_hitb2017ams.pdf">here</a>.

* By mounting the KARMA attack. This is a 10-year old attack that nowadays seems to work against iOS devices (and in some cases against Android too). Wifiphisher doesn't support KARMA yet. It's in our list though.

In other cases, user-interaction is required. We can annoy the victim user by DoS attacks that will hopefully make him click on the rogue WLAN by curiosity (same ESSID) or we can spawn an AP that supposedly servers a purpose (e.g. "Free WiFi").

**Comment by blackHatMonkey** [comment]
This has been implemented. If you feel that something is missing feel free to re-open this issue.
