### ISSUE TITLE
Credentials return incorrectly?

### ISSUE THREAD

**Issue by hellvetica42** [wifiphisher/wifiphisher#562]
Hello,
sorry for bothering but i'm getting some very weird issues with wifiphisher.
I'm testing out the debian based distro Parrot 3.5 with the latest commit of wifiphisher. I don't know if this happens in other distributions.

I'm trying to run the oauth-login attack on my home network.
The script starts fine. Creates a twin hotspot, deauthenticates clients and delivers the fake login page.
I do get all kinds of errors dumped all over the console once I open the webpage but they don't stop the functionality. As far as i can tell they are different every time, but here's an example:
```bash
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/deauth.py", line 168, in _send_deauthentication_packets
    self._socket.send(packet)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 36, in send
    return self.outs.send(sx)
```

When i open the page i type come credentials in they get returned like this:
```bash
POST 10.0.0.100 '--Nb4tC4duHzqHlIuj-yP7unGY-hRtL6NDClffudn\r\nContent-Disposition: form-data; name="protocver"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n1\r\n--Nb4tC4duHzqHlIuj-yP7unGY-hRtL6NDClffudn\r\nContent-Disposition: form-data; name="ran"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n455854\r\n--Nb4tC4duHzqHlIuj-yP7unGY-hRtL6NDClffudn\r\nContent-Disposition: form-data; name="sig"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n97fb2c20a18a19aa8ac975aef4effa1b\r\n--Nb4tC4duHzqHlIuj-yP7unGY-hRtL6NDClffudn\r\nContent-Disposition: form-data; name="flag"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n0\r\n--Nb4tC4duHzqHlIuj-yP7unGY-hRtL6NDClffudn\r\nContent-Disposition: form-data; name="data"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n{"module":"sdk_preferences","mcc":"219","sdkver":"1.14","appname":"iswipe","did":"cc41b1afe7ed7124","modulever":"5","language":"hr_HR","channel":"200001"}\r\n--Nb4tC4duHzqHlIuj-yP7unGY-hRtL6NDClffudn--\r\n'
```
However, form time to time, they do get returned correctly, but it's rare.
I couldn't find any fix online so any help would be appreciated.

**Comment by laozi999** [comment]
Did you change any of the python code?

**Comment by anakin1028** [comment]
@blackHatMonkey @laozi999 
Ｉgot similar problem, and I found that wifiphisher decode the post request with `utf8` by default in the file `phishingthttp.py`. But I don't know why after my phone is connecting to the fakeap, it sends a POST request which is encoded in `Latin-1`. So wifiphisher will get a exception from there.

The following is the snapshot I got from `pdb`
![aaa](https://cloud.githubusercontent.com/assets/6182530/25768677/26dc65d2-323b-11e7-81cd-d40a3029560c.png)

I can give a quick fix like the following:
```python
    try:
        post_data = tornado.escape.url_unescape(self.request.body)
    except UnicodeDecodeError:
         return
```
otherwise we have to figure what's the encoding method of this post request which maybe too much?
How do you guys think?

**Comment by sophron** [comment]
Maybe one of the reasons this is happening is because we don't set the "Content-Type" header. The Content-type header should contain a charset field to hint at the encoding, which should be UTF-8. We should be able to decode the content afterwards.

**Comment by blackHatMonkey** [comment]
@anakin1028 If your solution is implemented and you get a exception the post request is lost.

@sophron Is the Content-Type in the HTML or in Python code?

**Comment by anakin1028** [comment]
@blackHatMonkey yes. I also have a question will all the HTTP requests bring the `Content-Type`, what if it doesn't specify the `charset` field?

**Comment by sophron** [comment]
Hi guys,

In every response, our web server should set the `Content-Type: text/html; charset=utf-8` header. There is Tornado's `set_header` for this. All clients will sent requests in UTF-8 that we should be able to decode easily then. 

If however a browser insists on sending requests in different encoding, we should warn the user and still print it anyway. The user can decode it on his own after that point.

**Comment by anakin1028** [comment]
I try to do something like the following but my phone still send the non-decoded messages

```python
def post(self):
    def set_default_headers(self):
        super(CaptivePortalHandler, self).set_default_headers()        
        self.set_header('Content-Type', 'application/json')
```

@sophron I'm not sure I have catch your point, if the message cannot be decoded, how can we print it to users or you mean we just print the raw data to users, this seems meaningless?

The following is the output if decoded fail I'm currently implement, how do you guys think?
![decode_fail](https://cloud.githubusercontent.com/assets/6182530/25908726/7f3adc22-35dd-11e7-8cfa-a4c0773d2382.png)

**Comment by sophron** [comment]
@anakin1028 Is there a reason you are setting the `Content-Type` to `application/json`? You should set it to `text/html; charset=utf-8`, correct?

**Comment by anakin1028** [comment]
@sophron sorry my code is `charset` bit I mistype here...

**Comment by anakin1028** [comment]
@sophron @blackHatMonkey  I've done some packet analysis for this issue:

I found that my phone will send a `POST /mmtls` which brings a `applicantion/oct-stream content type` which is not a POST request for entering the passwords. The following is the capture for this POST request:

![pkt_decode_fail](https://user-images.githubusercontent.com/6182530/27008559-83f66500-4ea7-11e7-96ee-81dd22730f94.png)

And the oct-stream is not encoded in `utf-8` so this will cause our `unescape` process fail. You can see the `MediaType` section and try to decode the raw data with `utf-8` this will cause `UnicodeDecodeException`

And the normal POST request we should try to decode should be the following:
one can see the post URI is `/post` now.
![correct_post](https://user-images.githubusercontent.com/6182530/27008572-0660ceea-4ea8-11e7-875c-05517f216051.png)

Do you think we should do the POST header sanity check for this? I think this issue is not caused by the POST request for phishing the passwords but other POST requests sent by the devices.

**Comment by sophron** [comment]
Nice catch! Yes, that makes sense. We should check if this is a valid POST request for one of our phishing pages.

**Comment by talb21** [comment]
according to the user agent im thinking its the "wechat" application.
is it installed on your device?
