### ISSUE TITLE
Multiple suggestions

### ISSUE THREAD

**Issue by zxcvbnmlkjhgfd** [wifiphisher/wifiphisher#579]
Dear All, 
1 - please include a tutorial how we (as hackers/users) can integrate more (convincing) custom templates to use with Wifiphisher + include Samsung/Iphone/LG/HTC convincing interface and not use "please enter WPA Key" but rather "please enter your wireless password" ... not all people are tech know how to understand what WPA key means.

2 - logic problem: 
(correct logic as follows below)
a - deauthenticate
                               b - verify handshake
                               c - create the fake access point EXACTLY with the same MAC address as the victim access point and which shows a security (WPA-PSK) lock instead of (open)
                              d - weird ?! no .. you do not need to hammer the victim wifi with broadcast de-authentication all the time ... 90% probability he/she will restart the router and not fall for upgrade the phisihing firmware scheme.
                              e - if you want to hammer the victim in a clever manner, the firmware upgrade message should re-pop up again and again until the handshake is verified to be the true password. 

why?? because most victims will probably think a non-convincing phishing page such the one already included in wifiphisher is a scam and he/she will probably minimize it and continue their life on whatsapp or viber or facebook or instagram. Then they discover it is a fake access point because there's no internet connection in reality and they will think their router is acting up and then they will restart it. 

I hope this suggestion is taken into consideration because it is the result of actual phishing test. Thank you.

**Comment by blackHatMonkey** [comment]
Hi @zxcvbnmlkjhgfd 

>1 - please include a tutorial how we (as hackers/users) can integrate more (convincing) custom templates to use with Wifiphisher + include Samsung/Iphone/LG/HTC convincing interface and not use "please enter WPA Key" but rather "please enter your wireless password" ... not all people are tech know how to understand what WPA key means.

This is currently under works and should be done soon enough.

>a - deauthenticate

deauthentication is working fine now.

>verify handshake

This is something that could be implemented.

>create the fake access point EXACTLY with the same MAC address as the victim access point and which shows a security (WPA-PSK) lock instead of (open)

Mac address is irrelevant as the device will only look at the name of the access point(`ssid`) and it's encryption type. It is impossible to set the encryption to `WPA` and accept all passwords.

**Comment by zxcvbnmlkjhgfd** [comment]
@blackHatMonkey the a + b + c etc.. are not detached ideas, this is my idea of the logic that wiphisher should go through ... I do not make this suggestion to claim something of my property ... no, this is the result of using wiphisher or fluxion an implementation of the evil twin attack. 

I am actually surprised to know that mobile devices connect to networks using "essid" and not "bssid (mac change)" which is absurd. if the "essid" is changed, the user has to re-enter the password again for the network ?! ... I highly doubt it but I am not a programmer. Secondly, my aim was to only display the word "secure" instead of "open" for the fake SSID.  Thank you @blackHatMonkey

**Comment by blackHatMonkey** [comment]
@zxcvbnmlkjhgfd I by no means dismissed your idea.

>the a + b + c etc.. are not detached ideas, this is my idea of the logic that wiphisher should go through

The order is irrelevant since everything is setup is seconds if not milliseconds.  

>kindly not, the deauthentication phase should be smart not bruteforced because it is a critical psychological phase in tricking the victim

Perhaps a command line argument could be implemented to adjust the time between each deauthentication.

>I am actually surprised to know that mobile devices connect to networks using "essid" and not "bssid (mac change)" which is absurd. if the "essid" is changed, the user has to re-enter the password again for the network ?! 

A example of this would be a collage or university campus where a large area is getting covered. A single router can't possibly cover every spot therefore multiple routers are placed. Since there are multiple routers their MAC address is different however they broadcast the same `essid` and network type. The users don't have to connect to each router as they move through different zones and it's automatic. 

>Secondly, my aim was to only display the word "secure" instead of "open" for the fake SSID

Those are done by the operating systems. Having "HELLO WORLD secure" vs "HELLO WORLD" imho is worst but you could do it.

**Comment by laozi999** [comment]
@zxcvbnmlkjhgfd from what I understand you are trying to say that the current deauthentication method isn't good because the victim can simply reset the router? This means we need our jamming interface to repeatedly scan for the victim AP's channel & BSSID, because these can easily be changed. This issue has been raised several times in the past and I think it's already being worked on.

**Comment by zxcvbnmlkjhgfd** [comment]
thank you guys, looking forward to this !! you are not arrogant at all which is a good thing !! good work !!

**Comment by zxcvbnmlkjhgfd** [comment]
@laozi999 / @blackHatMonkey there's a little confusion here. there are 2 deauthentication scenarios taking place here, done in phases (succession). 
the first deauthentication phase when you kick the victim out of his genuine own router/AP, to get his mobile device to connect to your fake AP. the second deauthentication phase is when you hammer (jam) his genuine ap with broadcast deauthentication. 
This second phase is the problem, because it will lead the victim to restart his router/AP .. Why? because usually he will not be the only one using his AP but also members of his family, so if he you kick everyone from the genuine ap, well there's a common problem among on all the users of this router/AP and hence the victim will restart the router, it's the primal human instinct. 

(concept/research is one thing and proof of concept is a different thing ) So what do we do ?! answer, "smart deauthentication" !! how ? Wifiphisher should sense the closest/strong victim(s) (Tx/Rx/dbm) signal .. why? because this will be the client(s) that will provide the most accurate/correct handshake to verify against the input from the firmware update page. 
next we deauthenticate this victim once, he connects back to his AP and we capture a handshake. then we kick him again and this time we hammer the genuine AP with a deauthentication packet to forbid only this victim or victims ( with the strongest power signal) from accessing his genuine router/AP.

Once this victim or victims ( with the strongest client signal) are connected to our fake AP, the jamming of the genuine AP should stop because we do not want to disrupt the internet experience for other users which are not in the range of our fake AP. 
If the victim leaves our fake AP, the process is restarted again, however without recapturing the handshake phase because we already have it. Kindly read this post 3 times in order to get the idea .. I usually do that. Thank you

**Comment by vay3t** [comment]
I agree with the implementation of change mac. To have the same vendor. There are applications that detect this and it shows, just change the mac to an almost identical as in linset and change the last character of the mac. That would suffice

**Comment by minanagehsalalma** [comment]
@zxcvbnmlkjhgfd  i am with you in just one point  cloning the router mac address to make it have the same vendor  ![image](https://user-images.githubusercontent.com/20546638/30248990-28b25622-9632-11e7-874f-7f0bfc05922f.png)
but not changing the last character  as @vay3t   said because if the security type is the same the wifi will be 
Merged
![unticxctled](https://user-images.githubusercontent.com/20546638/30249424-aa1c5c4e-963c-11e7-9d46-86e69c047ee9.png)
 but change the second part of the mac address without touching the last character ex: aa-bb-cc-(dd-ff-e)e  and if it's possible change the characters between  the brackets to some thing familiar if it's q change it to o and if it's i change 1 or l to make sure if he saw mac address that isn't another router 
@blackHatMonkey @laozi999  why the  Ip of the router phishing page isn't 192.168.1.1 as every default get way router ip  .

**Comment by minanagehsalalma** [comment]
@zxcvbnmlkjhgfd  @blackHatMonkey @laozi999  i think   --mac-ap-interface option fix the first problem

**Comment by blackHatMonkey** [comment]
@minanagehsalalma 
> why the Ip of the router phishing page isn't 192.168.1.1 as every default get way router ip .

I think in the past it created some problems for the users and that's why it was changed to `10.0.0.1`

**Comment by sophron** [comment]
You can currently customize all IP addressing by editing the `wifiphisher/constants.py` file.

**Comment by minanagehsalalma** [comment]
@sophron  although i had changed the IP(s) in wifiphisher/constants.py file it didn't changed after starting wifiphisher .. a -ip option will be better and faster

**Comment by sophron** [comment]
You need to `python setup.py install` again or run wifiphisher as `python bin/wifiphisher` for your change to take effect.

**Comment by minanagehsalalma** [comment]
@sophron it worked but the -ip option  still  will be better and faster

**Comment by sophron** [comment]
Most of the times it's never going to be only one option; a user will want to configure the gateway, the mask/broadcast address etc. It doesn't hurt us to provide arguments for all these but it's not planned for the immediate future.
