### ISSUE TITLE
-iI raises exception with no known reason 

### ISSUE THREAD

**Issue by Jinovas** [wifiphisher/wifiphisher#649]
**Version**:
1.3
kali 4.9.0
wlan0 Intel Corporation Wireless 7260 (rev 5b)
wlan1 rt2800usb Ralink Technology, Corp. RT2870/RT3070

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.
```
sudo iwconfig
lo        no wireless extensions.

wlan1     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=30 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
wlan0     IEEE 802.11  ESSID:" "  
          Mode:Managed  Frequency:2.452 GHz  Access Point: 6C:B0:CE:FC:3D:EA   
          Bit Rate=1 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=67/70  Signal level=-43 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:55   Missed beacon:0
```

**Script output**: Paste the output of the tool, including any stack traces.

I get an exception raised but no actual reason given. Fresh install of wifiphisher from here, made sure all requirements were installed correctly. 

Also, my "wlan1" interface is not managed by network-manager so I bring it up with ifconfig in a mini script I use. "wlan0" is however managed by network-manager but even when I stop network-manager, I still get same error.

```
sudo wifiphisher -nJ -p firmeware_upgrade -iI wlan0 -aI wlan1 
[*] Starting Wifiphisher 1.3 at 2017-06-22 22:43
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 572, in start
    internet_interface = self.network_manager.set_internet_iface(args.internetinterface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher/common/interfaces.py", line 367, in set_internet_iface
    raise Exception
Exception
```

**Comment by mpkosewski** [comment]
just tried "sudo wifiphisher -aI wlan1 -nJ" and I get this =/ 

![forwifiphish](https://user-images.githubusercontent.com/13728103/27468488-f773b122-579e-11e7-887a-391587ca2c95.png)

**Comment by anakin1028** [comment]
About the second issue, can you help us use wireshark to capture the packets?
You can use the following commands:
```shell
iwconfig wlan0 mode montor
ifconfig wlan0 up
iwconfig wlan0 channel 11 #change 11 to the channel of target ap
```
I guess the problem is beacon is malformed, and we don't handle it properly.

**Comment by anakin1028** [comment]
we should have fixed this issue.I just forgot. Can you pull the latest commit and try again?

**Comment by anakin1028** [comment]
About the first issue, we don't support internet connection by wireless interface for V1.3. But you can pull the latest commit to use this feature.

**Comment by mpkosewski** [comment]
Yeah for sure! I can capture them after work. Just headed into work.

**Comment by anakin1028** [comment]
@mpkosewski thanks : ) After reading the code again, I guess you may have the same problem with the latest version. Besides from the capture, what adapter do you use as the jamming interface?

**Comment by mpkosewski** [comment]
Well I have all 3 of the main alfa cards lol but my favorite is the awus036nh (I think) it's the green one. I haven't gotten far enough to test the Jamming yet but that card does decent with the wifi jammer app on Github.

**Comment by anakin1028** [comment]
Yes. There is no problem for your card to do jamming, I'm a little misleading though. What I want to say is that we'll use the adapter to sniff the beacons and extract the RSSI from the beacon frames. Since RSSI info is vendor specific, so we may extract wrong position of the buffer for the beacon you captured.
Let's see if we can dig out something from your capture : )

**Comment by mpkosewski** [comment]
ok for sure! happy to help! It's been a min since I've worked with raw packets with scapy and making my own "probe sniffer" lol but I don't remember reading that the RSSI was very vendor specific? 

side note: I was hoping to use an actual equation with the help of my buddy who is a wiz at math, to measure the sniffed beacons and show an actual distance vs just a power level with estimating how far they are by visually analyzing the environment and making estimates lol

**Comment by anakin1028** [comment]
you can have a look at #478. We have a discussion there about the rssi problem. rssi is defined in the radiotap part and it is added by the vendor as an extra information, so the position of this may be vary between vendors.

**Comment by mpkosewski** [comment]
I apologize for being MIA. Wasn't feeling good most of the weekend and been swamped at work with no clue wtf i'm doing at work still lol I'll try to get those logs and do a lil more testing today. I headed home from work now.

**Comment by mpkosewski** [comment]
@anakin1028 good to know about the RSSI and vendor. I might have to collab with you on a project I've been working on on and off for a while now(I make too many damn projects for myself lol).

**Comment by mpkosewski** [comment]
Also, as a random question, do you guys not support wireless Internet connection because you use airmon-ng or another reason? I only ask because I've run into multiple popular tools that use airmon-ng which obviously breaks internet connectivity. I have a little script that works practically just as well and WON'T break the internet connection. Its nothing special or spectacular once you actually see it lol but it's worked perfectly with everything I've thrown at it.

Even got mana-toolkit working with that instead of eth0. 

Was just curious =]

**Comment by anakin1028** [comment]
@mpkosewski 

>  I might have to collab with you on a project I've been working on on and off for a while now(I make too many damn projects for myself lol).

We may use `wifiphisher` to see why there is a decoding error for the RSSI. I think you can use `wifiphisher` to reproduce this problem and in the meantime use `wireshark` or `tcpdump` to sniff the frames and post the capture in this thread. If you are interested in this problem, you can write simple script to listen the beacons by `scapy` and compare the raw packet format of decoding error beacon to the capture you got from `wireshark`.

> do you guys not support wireless Internet connection because you use airmon-ng or another reason?

We have supported this feature now. You can pull the latest commit and provide the internet interface as `-iI wlan0 #wlan0 is the internet interface`. 

In the `wifiphisher V1.3`, we use `airmon-ng check kill` to kill the interfering processes, so that why at that time we cannot use wireless interface as internet interface since NetworkManager is being killed. For now, we don't use it to kill the NetworkManager when `-iI` is given, but users have to set the AP/Deauth interfaces as `un-managed` in the `NetworkManager.conf`.

**Comment by mpkosewski** [comment]
> We may use wifiphisher to see why there is a decoding error for the RSSI. I think you can use wifiphisher to reproduce this problem and in the meantime use wireshark or tcpdump to sniff the frames and post the capture in this thread. If you are interested in this problem, you can write simple script to listen the beacons by scapy and compare the raw packet format of decoding error beacon to the capture you got from wireshark

Well the project I was referring too I'm building in pieces (as I learn how to do each part and then combine them into a much bigger more complex app. I am in a way trying to build my own version of airodump-ng but with more options like looking for specific vendor MAC's and giving an estimated measuable distance based of the "Free Space Path Loss" formula. 

> PATH LOSS(dB) = 32.44 + 20*log(F(MHz)) + 20*log(D(km)) - Gtx(dBi) - Grx(dBi)

I so far have a 1 liner done as a starting point (haven't touched it in a while). This one just scan's for wifi but same concept would apply for my device scanner. Somehow a while back I broke my device sniffer lol. pic attached of wifi scanner with scapy and RSSI levels:
![sofarscapy](https://user-images.githubusercontent.com/13728103/27618113-495cfa74-5b6f-11e7-8572-ea226d1ae8cf.png)

Looks like im gunna have to do some brushing up on my scapy haha xD

> In the wifiphisher V1.3, we use airmon-ng check kill to kill the interfering processes, so that why at that time we cannot use wireless interface as internet interface since NetworkManager is being killed. For now, we don't use it to kill the NetworkManager when -iI is given, but users have to set the AP/Deauth interfaces as un-managed in the NetworkManager.conf.

Right on. Yeah I had to do the same thing with mana. I haven't fully scripted everything out yet but I have all 3 Alfa wifi adapters saved and commented out except the one I don't want network-manager to manage. 

> We have supported this feature now. You can pull the latest commit and provide the internet interface as -iI wlan0 #wlan0 is the internet interface.


Oh sweet! I just now did so I'll play with it now and see what all happens =]

**Comment by mpkosewski** [comment]
so far still =/ everything looks ok though with wlan1 (AP adapter) in wireshark.
![wifiphishererror2](https://user-images.githubusercontent.com/13728103/27618376-e63f0c1e-5b70-11e7-8c7a-278069e68132.png)

**Comment by mpkosewski** [comment]
Ah ha! got it working it looks like! All I did was add a second wifi adapter to do the deauthing. This is as far as I got so far

the command I used was:
`sudo wifiphisher -aI wlan1 -iI wlan0 -jI wlan2 -p firmware_upgrade`

![wifiphisher_working](https://user-images.githubusercontent.com/13728103/27618649-67506766-5b72-11e7-9d18-397b2ac0a0cc.png)

So in short, I have...

1)  wlan0 (Built-in Intel wireless 7260) running internet
2)  wlan1 (Alfa AWUS036NH) running the AP
3)  wlan2 (Alfa AWUS036NHA) running the Deauth

**Comment by anakin1028** [comment]
> I so far have a 1 liner done as a starting point (haven't touched it in a while). This one just scan's for wifi but same concept would apply for my device scanner. Somehow a while back I broke my device sniffer lol. pic attached of wifi scanner with scapy and RSSI levels:

Again I guessed you need to observe from the capture and compare with raw packet format in `scapy`. For example: we assume the RSSI is in the `non-decoded` part `[-4:-3] or [-2:-1]` in `wifiphisher`.

> Ah ha! got it working it looks like! All I did was add a second wifi adapter to do the deauthing. This is as far as I got so far

Good to hear about that : )

**Comment by mpkosewski** [comment]
it broke again :( 

![wifiphisherbrokeagain](https://user-images.githubusercontent.com/13728103/27619625-b466861a-5b78-11e7-8f55-642f0a0420aa.png)

**Comment by anakin1028** [comment]
yes we have seen this issue in #608 and the purpose PR #656 should solve this issue.

**Comment by sophron** [comment]
I believe this issue no longer exists. Feel free to re-open if necessary.
