### ISSUE TITLE
AWUS036ACH Adapter

### ISSUE THREAD

**Issue by EOS123** [wifiphisher/wifiphisher#736]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by anakin1028** [comment]
@EOS123 I'm not aware of this adaptor. If this adaptor can support both `monitor` and `AP` then you only need this one to run `wifiphisher`.

**Comment by ssrmpc** [comment]
# Everybody that is using the 8812au driver PLEASE READ THIS!
First of all I send regards to all programmers on the project. WELL DONE!
After trying everything to get AWUS036ACH to work with fluxion and wifiphisher.... this is the conclusion for all interfaces that require the **realtek-rtl88xxau-dkms** (in my case the 8812au driver).
## Problem description
By installing apt-get install realtek-rtl88xxau-dkms you installed a driver based on [astam](https://github.com/astsam/rtl8812au) that does not correctly implement certain interfaces. Therefore this driver will never be part on the aircrack-ng project please read [THIS](https://aircrack-ng.blogspot.ch/2017/08/on-drivers-rtl8812au-wn722n-monitor.html).
Unfortunately the driver DOES NOT SUPPORT VIRTUAL INTERFACES (other than mode monitor). Therefore the fake AP created as virtual interface will always fail.
Problem solution

If you're really after 5G Networks YOU MUST USE 2 AWUS036ACH DEVICES. Like that the virtual interface  will not be created since wlan1 is used instead.

On my on regards
I kindly ask the responsible fluxion project manager to post my info as visible as possible. The bottomline is that the 8812au driver does not work properly! Therefore if you are new to Kali and to the wifi hacking topic DO NOT BUY ADAPTERS USING RTL8812AU! (Or buy two :-)
Thank you

**Comment by blackHatMonkey** [comment]
@ssrmpc Thanks for posting this. We will have to find a place for it in the documentation 👍 😄 .
