### ISSUE TITLE
Implement KARMA attack

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#76]
Right now wifiphisher uses the Evil Twin technique to trick the victim. 

Another very common technique to become MiTM is KARMA. Instead of creating an AP modeled on the target, we need to create an open network that the client has already connected to.

We can provide both options, Evil Twin and KARMA, and let the user make their choice.

**Comment by cicina** [comment]
hello, how is it going with KARMA attack? Will it be included?

**Comment by sophron** [comment]
It's not trivial to perform KARMA in Python (e.g. with Scapy). We may have to do tweaks in `hostapd` itself.  

This is not something that we have in our list for the upcoming v.1.3 but we may work on it in v1.4.

**Comment by kn0wledge** [comment]
@sophron @blackHatMonkey  is that up for version 1.3?  Karma is so much more effective and logical, its a wifiphisher, hence they should not be manually selecting their own network which they know has wpa whereas the rogue one will not. Karma makes it though as if they just disconnected and are auto reconnecting ... i feel this is a must have . what are your thoughts

**Comment by blackHatMonkey** [comment]
@kn0wledge unfortunately `v1.3` is set for release for April 13, 2017 and karma is not included in it. It would be in the next version.

**Comment by kn0wledge** [comment]
so unfortunate though... such a crucial feature.. with all the testing i made, success rates are low because when they have to manually connect: A - the realize something is wrong because they are not on wifi, and B - they realize their ssid does not have wpa ..... and then the scenario pops out... so not too subtle

**Comment by blackHatMonkey** [comment]
@kn0wledge Again I'm not sure how devices now days handle KARMA. I don't think it is as strong as it used be when it was first introduced. @sophron might have more information about this.

**Comment by kn0wledge** [comment]
i currently pentest with the wifi pineapple that implements karma attack, works pretty well so far. but @sophron would have a better idea.

**Comment by sophron** [comment]
KARMA is indeed not working in many devices as it used to. Automatic-association is definitely an important part of the attack process though.

Maybe we can implement KARMA in one of the future releases but for v1.3, we are planning to introduce <a href="http://conference.hitb.org/hitbsecconf2017ams/sessions/commsec-lure10-exploiting-windows-automatic-wireless-association-algorithm/">Lure10</a>.

**Comment by anakin1028** [comment]
@sophron 

> Another very common technique to become MiTM is KARMA. Instead of creating an AP modeled on the target, we need to create an open network that the client has already connected to.

As far as I know KARMA attack intercept the probe request from the victim and generate the probe response to them. If the victim is already connected to the original AP, will it connect to our Rogue AP simply because it receives our probe response?

Or I misunderstand the scenario for using KARMA attack?

**Comment by sophron** [comment]
In KARMA attack, the attacker responds positively to the "probe request frames" coming from the victim. The association process will continue (the client will sent an association request) until the attacker can determine if that probe request was intended for an open WLAN or a password-protected WLAN. In the case of a password-protected WLAN, the attacker will abort the association process. In the case of an open WLAN the attacker will proceed with authenticating the victim, hence achieving a man-in-the-middle.

Here are two different implementations of hostapd that perform the attack:

https://github.com/sensepost/hostapd-mana

https://github.com/OpenSecurityResearch/hostapd-wpe

If there are licensing issues, we may use one of the above versions of hostapd or we may need to patch hostapd ourselves. In any case, we will still need to make our own hostapd Python bindings to have better control of hostapd through Python (#569).

I have assigned myself to this, but feel free to do research / write code. :)

**Comment by anakin1028** [comment]
OK I may take a look about the above two projects since I'm not really familiar with KARMA attack. 

Can you also elaborate the meaning of Python binding? Do you mean we want to call the c function directly in Python? Also if we want to patch the hostapd this means we need to put the whole source code in wifiphisher, is this a proper way to do?

Another thing is I have seen the previous thread you and Brian discuss with the `fakeap` project, I have used this project before for doing some validation, and in this project since the beacon is sent by scapy this means that this frame have to pass from user space to kernel and then to HW, this will make the beacon interval very unstable. As the beacon is usually sent by HW directly. But I'm not sure this behavior will impact to KARMA attack.

**Comment by sophron** [comment]
> Can you also elaborate the meaning of Python binding? Do you mean we want to call the c function directly in Python?

Yes, if we can call C functions from Python that would be great.

> Do you mean we want to call the c function directly in Python? Also if we want to patch the hostapd this means we need to put the whole source code in wifiphisher, is this a proper way to do?

I believe it's better if we create a separate module and upload it to PyPi since other projects may benefit from it. Then we can install the module during installation (`python setup.py install`).

> in this project since the beacon is sent by scapy this means that this frame have to pass from user space to kernel and then to HW, this will make the beacon interval very unstable. As the beacon is usually sent by HW directly. But I'm not sure this behavior will impact to KARMA attack.

Yes, that's a valid observation too. My main point against `scapy-fakeap` is that we will have to re-invent the wheel. Implementing 802.11 specs in Python is a huge project that may end-up useless. Hostapd should work for us.

**Comment by anakin1028** [comment]
I have done some experiments with `hostapd-mana`:

Scenario1 : `hostapd-mana`'s SSID is different than the Target AP, then the victim will not connect to the `hostapd-mana`. Like the following capture:

Though `hostapd-mana`(the green-rectangle) sends the probe response, my laptop still connects to the target AP [The blue rectangle's mac address is the target's mac address].

![krama_attack](https://cloud.githubusercontent.com/assets/6182530/26112341/3e9ccc00-3a8a-11e7-8ac3-f246eab244c8.png)

Scenario2 : If the SSID are same, then the victim will connect to the `hostapd-mana`. 

So it seems that the ssid must be same so that the attack will be success? One of the scenario I can think is that if we know the users' PNL, then we can lunch `hostapd-mana` to the ssid in PNL. But this doesn't require with KARMA attack, only original `hostapd` can do such thing. So what's the value of KARMA attack?

**Comment by sophron** [comment]
@anakin1028 

KARMA attack is what you describe in Scenario 1. We see a probe-request and we respond with a probe-response. This will work only if that probe-request was intended for an OPEN network. And again, we need to have a better signal than the target AP.

> So it seems that the ssid must be same so that the attack will be success?

No, we need an ESSID from the victim's PNL that is also OPEN.

> One of the scenario I can think is that if we know the users' PNL, then we can lunch hostapd-mana to the ssid in PNL. But this doesn't require with KARMA attack, only original hostapd can do such thing. So what's the value of KARMA attack?

If we somehow know a WLAN from the victim's PNL that is Open, then we can still mount an attack using that WLAN. However, this requires this extra knowledge. The idea in KARMA is that we don't require any knowledge about the victim (we don't know victim's PNL) and still get man-in-the-middle.

The <a href="http://theta44.org/karma/aawns.pdf">KARMA whitepaper</a> is a good read.

**Comment by anakin1028** [comment]
@sophron Thanks for the detail explanation

I'll read this whitepaper. But in the scenario 1 I have described, my target AP[`ssid=haha, mac address=00:00:00:ab:af:8c`] has been lunched as OPEN AP, as you can see in the capture, my laptop still connects to the target AP instead of the `hostapd-mana` which has replied the probe response to my laptop as in the green rectangle in my capture.

So is this because `hostapd-mana`'s signal weaker than my target AP?

**Comment by sophron** [comment]
> So is this because hostapd-mana's signal weaker than my target AP?

Yes, that could be one reason. If the probe response frame of the target AP is processed first by the victim's network card, it will prefer it. 

This scenario can be simulated as following: Turn off Wi-Fi on your device. Spawn two OPEN WLANs that exist in your device's PNL. Turn on Wi-Fi discovery process. 

In general, network managers behave differently in KARMA. Windows devices are by default not vulnerable, because they don't add any OPEN networks in the PNL. In my experience, iOS and Android devices appear to be mostly vulnerable nowdays.

Here's the relevant presentation on Defcon by SensePost: https://www.youtube.com/watch?v=i2-jReLBSVk

**Comment by sophron** [comment]
KARMA is now featured in Wifiphisher! Go test it and let us know of any bugs.
