### ISSUE TITLE
KRACK Attacks

### ISSUE THREAD

**Issue by yungtravla** [wifiphisher/wifiphisher#791]
https://github.com/wifiphisher/wifiphisher/issues/786

Either don't close the issue prematurely and answer my questions or point me somewhere I can discuss these things without it being rejected due to lack of knowledge/vocabulary understanding.

**Comment by anakin1028** [comment]
Hi, we have supported `KARMA attack`. You can do `pip install roguehostapd` first and that module will replace with the `hostapd` installed on the system.

Another thing is I haven't followed the issues you have mentioned before. I personally think our members all like to discuss about the technical issues and indeed some of issues you mention may cause users inconvenient, but you should remember one thing, this is just an open source project every member may choose the interested part to purpose PR. Like me, I like wireless stuffs so my PRs will usually focus on the wireless side. Also the `five line issue` you open (#775) has been mentioned before (#704), I think this issue is just a duplicated one.

When discussing the issues I think we should better not bring the emotional feeling, since this often causes the misunderstanding. Many of us don't speak English as the primary language, so we may not understand your joking words. 

About KRACK attack, I haven't had time to see this stuff, but I think @sophron has the right to determine whether it is suitable for doing this. For me I think every password cracking feature is not suitable for this project. For one thing is performance issue. This is a `Python` project, we cannot do the `WPA2` cracking like `aircrack-ng` which is developed in `C`. We also need to consider whether this feature will make our project so diverged since our project focus on use rogue AP to do phishing stuffs.

Last word, when I write this, I have no offending feeling.

Thanks

**Comment by usama7628674** [comment]
Most of the devices and OS are updated and so KRACK attack will become useless after some time.Why waste time on writing a script that doesn't work in the future?I agree with @anakin1028 and not every attack can be implemented in this project cuz this is all about phishing and rogue AP.

**Comment by usama7628674** [comment]
Most of the devices and OS are updated and so KRACK attack will become useless after some time.Why waste time on writing a script that doesn't work in the future?I agree with @anakin1028 and not every attack can be implemented in this project cuz this is all about phishing and rogue AP.

**Comment by yungtravla** [comment]
@usama7628674 said:

> Why waste time on writing a script that doesn't work in the future?

https://www.krackattacks.com said:

> Is it sufficient to patch only the access point? Or to patch only clients?
> 
> Currently, all vulnerable devices should be patched. In other words, patching the AP will not prevent attacks against vulnerable clients. Similarly, patching all clients will not prevent attacks against vulnerable access points. Note that only access points that support the Fast BSS Transition handshake (802.11r) can be vulnerable.
> 
> That said, it is possible to modify the access point such that vulnerable clients (when connected to this AP) cannot be attacked. However, these modifications are different from the normal security patches that are being released for vulnerable access points! So unless your access point vendor explicitly mentions that their patches prevent attacks against clients, you must also patch clients.

This is not gonna be patched soon with the amount of different devices and vendors out there.

**Comment by sophron** [comment]
As I said in the previous thread, KRACK attacks are not in our scope. 

We only care about rogue Access Point attacks or Wi-Fi automatic association attacks and anything else regarding these. The tool's main target is not really a wireless network, but wireless stations instead.

**Comment by yungtravla** [comment]
@anakin1028

> When discussing the issues I think we should better not bring the emotional feeling, since this often causes the misunderstanding. Many of us don't speak English as the primary language, so we may not understand your joking words.

I respect that and I agree with you. Thanks for regarding all my points too.

When I write comments that step on people's toes, I'm just being overly direct (and sometimes having a laugh). 

But when I see a certain issue that's been repeatedly reported by a multitude of users, and persists over months on end, and then I read (for example) @sophron defending the choice of restricting our output to 5 lines per stream, I don't sense much open-source dev going on.

I also might have taken things too personally, but my critique is not meant to point fingers at anyone, but to identify (potential) issues.

**Comment by anakin1028** [comment]
Sure. BTW we have added the `--logging` option though the output screen still limit 5 lines. When using --logging, all the important info should be preserved.
