### ISSUE TITLE
Please guide about best wireless adpater for wifiphisher

### ISSUE THREAD

**Issue by AnEvilInsideMe** [wifiphisher/wifiphisher#793]
Can anyone tell me that which wireless adapter supports AP mode ?? I bought _**Tl-WN727N**_ but its only support monitor mode now i have to buy a wireless adapter which supports AP mode. If an adapter supports AP mode and also Monitor mode so please tell me about that.

**Comment by anakin1028** [comment]
@AnEvilInsideMe 
I personally test wifiphisher with the following adaptors:
1. AWUS036NHA
2. WN722N-V1 (Be aware you should by version 1 and not the version 2)

**Comment by AnEvilInsideMe** [comment]
These both adapters support AP and Monitor mode ??

**Comment by ssrmpc** [comment]
Do not use Adapters that use realtek-rtl88xxau-dkms driver, since that
driver does not support virtual adapter creating.

You may use Panda 300Mbps or Panda 600 that goes up to 5G with the native
Kali Realtek-Drivers. Never the less I have an affinity to the Atheros
drivers. Since that WN722N has a version 2 that doesn't have the Atheros
chipset and nobody can guarantee that you'll get version 1 I bought the Alfa*
AWUS036NHA. *I am quite happy with my setup

Don't forget to buy 2 adapters..... that's sometimes needed.

Chers
Marc

2017-10-28 6:30 GMT+02:00 AnEvilInsideMe <notifications@github.com>:

**Comment by AnEvilInsideMe** [comment]
Thank you

**Comment by yoghurtslinger** [comment]
try running this command, then running the wifiphisher command again afterwards

sudo airmon-ng check kill
