### ISSUE TITLE
Stealth option

### ISSUE THREAD

**Issue by yungtravla** [wifiphisher/wifiphisher#811]
The `-qS` option is crucial as it can make all the difference on whether an attack will be successful or not. 

What are people's thoughts on a `-sM` (`--stealthmode`) feature that will prepare everything for an attack, but only start the attack once we're sure that a client is interacting with the target AP? (And of course also pause the attack when everything appears idle)

**Comment by yungtravla** [comment]
idle as in no one is trying to perform a handshake with the target AP for 2 seconds.

**Comment by sophron** [comment]
Hi,

What would be the benefit of starting the attack only when the victim users are active? How does it make the attack stealthy?

**Comment by yungtravla** [comment]
why would you fish in a lake you know has no fish?

**Comment by yungtravla** [comment]
and what good would broadcasting a rogue (and perhaps in some cases illegel) access point do for everyone to see, when it's pointless to begin with?

**Comment by sophron** [comment]
> why would you fish in a lake you know has no fish?

There are fish; they are just sleeping.

> and what good would broadcasting a rogue (and perhaps in some cases illegal) access point do for everyone to see, when it's pointless to begin with?

An automatic association attack has actually more chances to go unnoticed when the victim user doesn't interact with his device during the attack (Network Manager UI notifications are bypassed).

Let me reverse the question again: What is the benefit of starting the attack only when the victim users are active? A WIDS should detect the attack either way.

**Comment by yungtravla** [comment]
Are you being serious at the moment?

The fish are sleeping?? The fish might be on a holiday, and their neighbours might hate fishers... You're not considering every type of scenario.

And since wifiphisher is meant for phishing user input, why are you talking about an attack with no user interaction?

I'll say it even simpler for you: Wifiphisher is absolutely pointless unless there is a victim. Why broadcast anyway?

**Comment by yungtravla** [comment]
it's a total waste of cpu and could potentially cause legal troubles (if used incorrectly).

**Comment by yungtravla** [comment]
and I was not even talking about WIDS... Which is actually a pretty solid reason not to use wifiphisher

**Comment by sophron** [comment]
> Are you being serious at the moment?

Yes. 

> The fish are sleeping?? The fish might be on a holiday,

Wifiphisher is a penetration testing tool. I'm not sure how the company or organization can be "on holiday" during a tiger-team testing. But let's suppose a scenario that Wifiphisher is running in a Raspberry Pi device hidden somewhere in the target organization infrastructure. Let's also suppose that remote connection is not possible. Indeed, for efficiency reasons only, the optimal way would be for Wifiphisher not to operate when there's noone in the infrastructure (i.e. during the night). Instead of ruining the chance of automatic association during the day, I would prefer to completely stop the tool from running during the night (e.g. using a cron-like scheduler).

>  and their neighbours might hate fishers... You're not considering every type of scenario.

A wireless security tester should target only specific Access Points that are part of the testing (e.g. by using the `--essid` option). 

> it's a total waste of cpu and could potentially cause legal troubles (if used incorrectly).

Again, a wireless security tester will target specific BSSIDs. I don't see any legal issues. 

> I'll say it even simpler for you: Wifiphisher is absolutely pointless unless there is a victim. Why broadcast anyway?

What you are failing to understand is that there is no way to determine if there are no victims around vs victims that are around but are NOT actively using their devices.

> And since wifiphisher is meant for phishing user input, why are you talking about an attack with no user interaction?

Automatic association with no user interaction is one thing. Phishing victims is another. They can happen at different times and they are not necessarily interrelated (a man-in-the-middle attack doesn't always lead to phishing).

Your language is not welcoming. I'm not planning to spend more time explaining to you how things work if you keep this attitude.

**Comment by yungtravla** [comment]
This is absolutely going nowhere.. I've explaines to you the works and benefit of a stealthier approach, but you fail to address my main point.

I have stopped using wifiphisher a while ago as it is extremely limited and not safe to use in my opinion.

Take my advice, or don't. This was the last of my efforts to contribute to this project.

All the best.

Peace

**Comment by yungtravla** [comment]
@sophron said

> Your language is not welcoming. I'm not planning to spend more time explaining to you how things work if you keep this attitude.

My guess is that you still carry hard feelings due to the fact that I blatantly made fun of some of the idiotic limitations presented in this tool.

And I rest my case, some things about this tool are to be ridiculed for as long as they persist.

Adios

**Comment by yungtravla** [comment]
nice logo however :)
