### ISSUE TITLE
Why not phish wifi directly as if it was a protected Network, it is more convincing than web form.

### ISSUE THREAD

**Issue by IvanTurgenev** [wifiphisher/wifiphisher#882]
Is it not technically possible?

Also why it doesnt present itlself as a wifi login like when you connect to an airport wifi and if says wifi needs authentications that way it automatically opens the web form, mobile users check wifi opening whatsapp of facebook not opening chrome

**Comment by JetseVerschuren** [comment]
1. When you connect the access point needs to give cryptographic proof to the client that it knows the password.
2. It should automatically popup.

**Comment by IvanTurgenev** [comment]
jmm cool if we could get some explanation in my mind it still seems possible

**Comment by JetseVerschuren** [comment]
Ok, the problem is that when you authenticate to protected wifi your device sends a [hash](https://en.wikipedia.org/wiki/Cryptographic_hash_function) of your password to the access point. So that way the password is never actually sent over the network. The second problem is that the client wants cryptographic proof from the access point that it knows the password so we can't just accept all password we actually need to know the password.

**Comment by sophron** [comment]
@IvanTurgenev Please read the <a href="http://wifiphisher.readthedocs.io/en/latest/faq.html">FAQ</a>.
