### ISSUE TITLE
ImportError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by dedm1** [wifiphisher/wifiphisher#925]
![image](https://user-images.githubusercontent.com/23456353/40276774-e45d5928-5c3c-11e8-8db1-610d031b9373.png)
![image](https://user-images.githubusercontent.com/23456353/40276777-f4d99c80-5c3c-11e8-9677-70eec6c711b8.png)
ImportError: No module named 'ConfigParser'
open in pyton3 and pyton 2
 alias  python=python2

**Comment by dedm1** [comment]
sudo  python=python2
and (главным сделать питон 2 спасибо ребята)

**Comment by blackHatMonkey** [comment]
@dedm1 Thanks for opening an issue. It seems that it is trying to run `wifiphisher` under `python 3`. Can you install the latest from `github`. You can follow [this](http://wifiphisher.readthedocs.io/en/latest/?badge=latest#c-install-from-source) if you are not sure how to.

**Comment by sophron** [comment]
^ What they said.

**Comment by Punksolid** [comment]
Same error, I'm installing it now under python2 and works, but found that upgrading to python3 may be easy https://stackoverflow.com/questions/14087598/python-3-importerror-no-module-named-configparser

**Comment by Talismancer** [comment]
Don't go to python2 or you'll have version compatibility issues when running wifiphisher
Compiling under python3 requires changing line 10 of roguehostapd/config/hostapdconfig.py because SafeConfigParser is deprecated.
Replace line 10 with:
from configparser import ConfigParser as SafeConfigParser

The next problem is that when you attempt to run wifiphisher (after you've got past it's compile problems), you'll get an error:
ModuleNotFoundError: No module named 'roguehostapd.apctrl'
You need to manually copy apctrl.py and the 'config' directory into the correct location:

cd roguehostapd/roguehostapd
sudo cp apctrl.py /usr/local/lib/python3.13/dist-packages/roguehostapd/apctrl.py
sudo cp -r config /usr/local/lib/python3.13/dist-packages/roguehostapd/

sudo wifiphisher --help

**Comment by Anonymus-arch** [comment]
I gone to this folder to change the line 10 of hostapdconfig.py but it was empty
/tmp/easy_install-56035t78/wifiphisher-roguehostapd-381b373/roguehostapd/config/hostapdconfig.py
